update z_datasets set intname = 'tab_Comm' where intname = 'Общие данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_DCards')
update z_datasets set intname = 'tab_List' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Comm' where intname = 'Общие данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_PClass' where intname = 'Классификация' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_MQ' where intname = 'Виды упаковок' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_M_PP' where intname = 'Партии' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_M_PL' where intname = 'Цены продажи' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_AutoCh' where intname = 'Автоизменение цен' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Prices' where intname = 'Цены' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Norms' where intname = 'Нормы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_More1' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Alts' where intname = 'Альтернативы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_ProdEC' where intname = 'Внешние коды' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Values' where intname = 'Значения периодов' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Crts' where intname = 'Сертификаты' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'TabSheet3' where intname = 'Сертификаты партий ' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Sets' where intname = 'Комплекты' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_SetD' where intname = 'Комплектация' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_SExp' where intname = 'Разукомплектация' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_SetC' where intname = 'Затраты на 1 комплект' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_ProdValues' where intname = 'Значения' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Images' where intname = 'Изображения' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'TabSheet1' where intname = 'Товар' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_PCstRec')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_PCstRec')
update z_datasets set intname = 'ctl_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_PCstRec')
update z_datasets set intname = 'ctl_Tax' where intname = 'Налоговая' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_PCstRec')
update z_datasets set intname = 'tab_Comm' where intname = 'Товар' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_PCustom')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_PCustom')
update z_datasets set intname = 'ctl_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_PCustom')
update z_datasets set intname = 'tab_Tax' where intname = 'Налоговая' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_PCustom')
update z_datasets set intname = 'TabSheet2' where intname = 'Первичные данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_EVen')
update z_datasets set intname = 'ctl_Params' where intname = 'Настройки' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_PDoc')
update z_datasets set intname = 'TabSheet1' where intname = 'Товар' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_SEst')
update z_datasets set intname = 'TabSheet2' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_SEst')
update z_datasets set intname = 'tab_Props' where intname = 'Настройки' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_SEst')
update z_datasets set intname = 'tab_Main2' where intname = 'Подробно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_OrderDistrib')
update z_datasets set intname = 'ctl_Params' where intname = 'Настройки' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_OrderExtNew')
update z_datasets set intname = 'tab_Sets' where intname = 'Комплекты' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_SetDoc')
update z_datasets set intname = 'tab_SubSets' where intname = 'Составляющие комплекта' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_SetDoc')
update z_datasets set intname = 'tab_SubSet1Costs' where intname = 'Затраты на 1 комплект' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_SetDoc')
update z_datasets set intname = 'tab_CreateSets' where intname = 'Работа с комплектами' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_SetDoc')
update z_datasets set intname = 'tab_Cost' where intname = 'Общие затраты' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_SetDoc')
update z_datasets set intname = 'TabSheet2' where intname = 'Итоги' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_SetDoc')
update z_datasets set intname = 'TabSheet3' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tft_SetDoc')
update z_ToolPages set intname = 'tab_PP' where intname = 'Цены прихода' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorEst')
update z_ToolPages set intname = 'tab_Cost' where intname = 'Себестоимость' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorEst')
update z_ToolPages set intname = 'tab_Info' where intname = 'Цены продажи' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorEst')
update z_ToolPages set intname = 'tab_ExtraCat' where intname = 'Категории наценки' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorEst')
update z_ToolPages set intname = 'tab_Info' where intname = 'Цены продажи' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorExtra')
update z_ToolPages set intname = 'tab_ExtraCat' where intname = 'Категории наценки' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorExtra')
update z_ToolPages set intname = 'tab_Comm' where intname = 'Общие' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorImages')
update z_ToolPages set intname = 'tab_Comm' where intname = 'Общие' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorOrd')
update z_ToolPages set intname = 'tab_PP' where intname = 'Партии' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorProd')
update z_ToolPages set intname = 'tab_PL' where intname = 'Цены продажи' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorProd')
update z_ToolPages set intname = 'tab_Rem' where intname = 'Текущие остатки' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorProd')
update z_ToolPages set intname = 'tab_RemPP' where intname = 'Партии и остатки' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorProd')
update z_ToolPages set intname = 'tab_UM' where intname = 'Виды упаковок' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorProd')
update z_ToolPages set intname = 'tab_Alts' where intname = 'Альтернативы' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorProd')
update z_ToolPages set intname = 'tab_Image' where intname = 'Изображение' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorProd')
update z_ToolPages set intname = 'tab_Balance' where intname = 'Баланс' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorRet')
update z_ToolPages set intname = 'tab_Inv' where intname = 'Расходная накладная' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorRet')
update z_ToolPages set intname = 'tab_Exp' where intname = 'Расходный документ' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorRet')
update z_ToolPages set intname = 'tab_Rec' where intname = 'Приход товара' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorRet')
update z_ToolPages set intname = 'tab_Ret' where intname = 'Возврат товара' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_MonitorRet')
update z_ToolPages set intname = 'tab_Comm' where intname = 'Общие данные' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tft_ProdFind')
update z_datasets set intname = 'tab_List' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Comm' where intname = 'Общие данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_PClass' where intname = 'Классификация' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_M_PP' where intname = 'Партии' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_M_PL' where intname = 'Цены продажи' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Prices' where intname = 'Цены' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Norms' where intname = 'Нормы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_More1' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Crts' where intname = 'Сертификаты' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'TabSheet3' where intname = 'Сертификаты партий ' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_Sets' where intname = 'Комплекты' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_SetD' where intname = 'Комплектация' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_SExp' where intname = 'Разукомплектация' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_SetC' where intname = 'Затраты на 1 комплект' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Prods')
update z_datasets set intname = 'tab_V' where intname = 'Общие' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_AssRepair')
update z_datasets set intname = 'tab_P' where intname = 'ТМЦ' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_AssRepair')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_AssRepair')
update z_datasets set intname = 'ctl_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_AssRepair')
update z_datasets set intname = 'TabSheet1' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Assets')
update z_datasets set intname = 'tab_Main' where intname = 'Общие данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Assets')
update z_datasets set intname = 'tab_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Assets')
update z_datasets set intname = 'tab_Comm' where intname = 'ТМЦ' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_Acc')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_Acc')
update z_datasets set intname = 'ctl_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_Acc')
update z_datasets set intname = 'tab_List' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_HandTran')
update z_datasets set intname = 'tab_DAnal' where intname = 'Аналитика дебета' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_HandTran')
update z_datasets set intname = 'tab_CAnal' where intname = 'Аналитика кредита' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_HandTran')
update z_datasets set intname = 'tab_Filter' where intname = 'Фильтр' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_HandTran')
update z_datasets set intname = 'TabSheet1' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_TaxInvOut')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_TaxInvOut')
update z_datasets set intname = 'ctl_Params' where intname = 'Настройки' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_TaxInvOut')
update z_datasets set intname = 'tab_Main' where intname = 'Общие' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_WayBill')
update z_datasets set intname = 'tab_Tasks' where intname = 'Задания водителю' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_WayBill')
update z_datasets set intname = 'tab_RWork' where intname = 'Результаты работы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_WayBill')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_WayBill')
update z_datasets set intname = 'ctl_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_WayBill')
update z_datasets set intname = 'TabSheet1' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Cars')
update z_datasets set intname = 'tab_Carrs' where intname = 'Общие данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Cars')
update z_datasets set intname = 'tab_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Cars')
update z_datasets set intname = 'tab_V' where intname = 'Общие' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRep')
update z_datasets set intname = 'tab_P' where intname = 'ТМЦ' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRep')
update z_datasets set intname = 'tab_S' where intname = 'Основные средства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRep')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRep')
update z_datasets set intname = 'ctl_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRep')
update z_datasets set intname = 'ctl_Tax' where intname = 'Налоговая' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRep')
update z_datasets set intname = 'tab_V' where intname = 'Общие' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRepCodes')
update z_datasets set intname = 'tab_P' where intname = 'ТМЦ' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRepCodes')
update z_datasets set intname = 'tab_S' where intname = 'Основные средства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRepCodes')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRepCodes')
update z_datasets set intname = 'ctl_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRepCodes')
update z_datasets set intname = 'ctl_Tax' where intname = 'Налоговая' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_CashRepCodes')
update z_datasets set intname = 'tab_Comm' where intname = 'ТМЦ' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PAcc')
update z_datasets set intname = 'tab_MoreComm' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PAcc')
update z_datasets set intname = 'ctl_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PAcc')
update z_datasets set intname = 'ctl_Tax' where intname = 'Налоговая' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PAcc')
update z_datasets set intname = 'TabSheet4' where intname = 'Списание ТМЦ' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PCost')
update z_datasets set intname = 'TabSheet5' where intname = 'Прочие расходы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PCost')
update z_datasets set intname = 'tab_DocD_Exp' where intname = 'Прочие расходы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PCost')
update z_datasets set intname = 'pan_RunCalc' where intname = 'Расчет себестоимости' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PCost')
update z_datasets set intname = 'TabSheet1' where intname = 'ТМЦ' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PCstRec')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PCstRec')
update z_datasets set intname = 'ctl_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PCstRec')
update z_datasets set intname = 'ctl_Tax' where intname = 'Налоговая' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_PCstRec')
update z_datasets set intname = 'ctl_Params' where intname = 'Настройки' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_ProdIn')
update z_datasets set intname = 'TabSheet1' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_SalaryIn')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_SalaryIn')
update z_datasets set intname = 'ctl_FundsInfo' where intname = 'По фондам' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_SalaryIn')
update z_datasets set intname = 'TabSheet1' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_SalaryOut')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfb_SalaryOut')
update z_ToolPages set intname = 'tab_PP' where intname = 'Партии' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorProd')
update z_ToolPages set intname = 'tab_PL' where intname = 'Цены продажи' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorProd')
update z_ToolPages set intname = 'tab_Rem' where intname = 'Текущие остатки' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorProd')
update z_ToolPages set intname = 'tab_RemPP' where intname = 'Партии и остатки' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorProd')
update z_ToolPages set intname = 'tab_Balance' where intname = 'Баланс' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorRet')
update z_ToolPages set intname = 'tab_Inv' where intname = 'Расходная накладная' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorRet')
update z_ToolPages set intname = 'tab_Exp' where intname = 'Расходный документ' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorRet')
update z_ToolPages set intname = 'tab_Rec' where intname = 'Приход товара' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorRet')
update z_ToolPages set intname = 'tab_Ret' where intname = 'Возврат товара' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorRet')
update z_datasets set intname = 'TabSheet1' where intname = 'Данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfc_Salary')
update z_ToolPages set intname = 'ctl_GAAP' where intname = 'Операция' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorTran')
update z_ToolPages set intname = 'ctl_FistEvent' where intname = 'Первое событие' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfb_MonitorTran')
update z_datasets set intname = 'tab_Comm' where intname = 'Общие данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_StdRef')
update z_datasets set intname = 'tab_Comm' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfz_StdDoc')
update z_datasets set intname = 'tab_List' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Comps')
update z_datasets set intname = 'tab_Comm' where intname = 'Общие данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Comps')
update z_datasets set intname = 'tab_Contacts' where intname = 'Контакты' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Comps')
update z_datasets set intname = 'tab_BankCC' where intname = 'Расчетные счета' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Comps')
update z_datasets set intname = 'tab_BankMC' where intname = 'Валютные счета' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Comps')
update z_datasets set intname = 'tab_Templates' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Comps')
update z_datasets set intname = 'tab_Docs' where intname = 'Документы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Comps')
update z_datasets set intname = 'tab_Addresses' where intname = 'Адреса доставки' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Comps')
update z_datasets set intname = 'tab_Discount' where intname = 'Дисконтные карты' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Comps')
update z_datasets set intname = 'tab_CompValues' where intname = 'Значения' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Comps')
update z_datasets set intname = 'tab_List' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_Comm' where intname = 'Общие данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_More' where intname = 'Дополнительно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_Contact' where intname = 'Контакты' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_Kin' where intname = 'Семейное положение' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_Act' where intname = 'Трудовая деятельность' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_Ours' where intname = 'Фирмы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_Priv' where intname = 'Льготы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_Mil' where intname = 'Воинский учет' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_EmpNames' where intname = 'Изменение ФИО' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_EmpMPst' where intname = 'Кадровое состояние' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_datasets set intname = 'tab_EmpFiles' where intname = 'Документы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Emps')
update z_ToolPages set intname = 'tab_List' where intname = 'Список' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfz_DocLinks')
update z_ToolPages set intname = 'tab_ChildDocs' where intname = 'Подчиненные документы' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfz_MonitorDoc')
update z_ToolPages set intname = 'tab_ParentDocs' where intname = 'Основополагающие документы' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfz_MonitorDoc')
update z_ToolPages set intname = 'tab_ProcsPlan' where intname = 'Процессы' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfz_MonitorDoc')
update z_ToolPages set intname = 'tab_Comm' where intname = 'tab_Comm' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfz_RefSelect')
update z_ToolPages set intname = 'ctl_CopyLists' where intname = 'Наборы' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_DestSourceMode' where intname = 'tab_DestSourceMode' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_SrcStructura' where intname = 'tab_SrcStructura' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_Parametrs' where intname = 'tab_Parametrs' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_Fields' where intname = 'tab_Fields' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_Formuls' where intname = 'Формулы' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_Param' where intname = 'Фильтры' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_SortField' where intname = 'tab_SortField' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_DestFiled' where intname = 'tab_DestFiled' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_VarPosID' where intname = 'tab_VarPosID' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_MoreParam' where intname = 'Дополнительные параметры копирования' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_Script' where intname = 'Скрипты' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_Base' where intname = 'База' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_StartInfo' where intname = 'tab_StartInfo' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_UserRadioButton' where intname = 'tab_UserRadioButton' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_CheckBoxes' where intname = 'tab_CheckBoxes' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_MoreUserParams' where intname = 'Фильтры пользователя' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_ToolPages set intname = 'tab_Start' where intname = 'tab_Start' and toolcode in (select toolcode from z_Tools s join z_ToolRep d on s.reptoolcode = d.reptoolcode and formclass = 'Tfs_WCopyE')
update z_datasets set intname = 'tab_DetPages' where intname = 'Подробно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_CommunalTax')
update z_datasets set intname = 'tab_Main' where intname = 'Основное' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_DocSick')
update z_datasets set intname = 'tab_Dates' where intname = 'Данные о заработке' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_DocSick')
update z_datasets set intname = 'tab_SumE' where intname = 'Пособие (по месяцам)' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_DocSick')
update z_datasets set intname = 'tab_AdvRep' where intname = 'Авансовый отчет' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_DocTrip')
update z_datasets set intname = 'tab_Main' where intname = 'Основное' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_DocWrit')
update z_datasets set intname = 'tab_Addr' where intname = 'Получатель' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_DocWrit')
update z_datasets set intname = 'tab_Pays' where intname = 'Удержания' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_DocWrit')
update z_datasets set intname = 'tab_LRec' where intname = 'Начисления' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_EmpIn')
update z_datasets set intname = 'tab_LExp' where intname = 'Выплаты' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_EmpIn')
update z_datasets set intname = 'tab_WTime' where intname = 'Отработанное время' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_EmpIn')
update z_datasets set intname = 'tab_Leavs' where intname = 'Отпуска' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_EmpIn')
update z_datasets set intname = 'tab_List' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_LeaveSched')
update z_datasets set intname = 'tab_List' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_MoveDays')
update z_datasets set intname = 'tab_List' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_PostStruc')
update z_datasets set intname = 'tab_VacOcc' where intname = 'Занятых должностей' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_PostStruc')
update z_datasets set intname = 'tab_VacFree' where intname = 'Свободных должностей' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_PostStruc')
update z_datasets set intname = 'ctl_Main' where intname = 'Свойства' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_PostStruc')
update z_datasets set intname = 'tab_MainSched' where intname = 'Основной график' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_WorkTime')
update z_datasets set intname = 'tab_ExtSched' where intname = 'Дополнительные графики' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_WorkTime')
update z_datasets set intname = 'tab_Info' where intname = 'Основное' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_CallToWork')
update z_datasets set intname = 'tab_Main' where intname = 'Основное' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_OrderDismiss')
update z_datasets set intname = 'tab_Salary' where intname = 'Расчетные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_OrderDismiss')
update z_datasets set intname = 'tab_DocDP' where intname = 'Данные помесячно' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_OrderLeave')
update z_datasets set intname = 'tab_DocDD' where intname = 'Данные о выплатах' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_OrderLeave')
update z_datasets set intname = 'tab_Main' where intname = 'Основное' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_OrderMove')
update z_datasets set intname = 'tab_Salary' where intname = 'Зарплата' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_OrderMove')
update z_datasets set intname = 'tab_Comm' where intname = 'Основное' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_OrderTrip')
update z_datasets set intname = 'tab_List' where intname = 'Список' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Candidates')
update z_datasets set intname = 'tab_Comm' where intname = 'Общие данные' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Candidates')
update z_datasets set intname = 'tab_CandidateFiles' where intname = 'Документы' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfr_Candidates')
update z_datasets set intname = 'tab_PayTypes' where intname = 'Типы выплат' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_SalaryIn')
update z_datasets set intname = 'tab_Cor' where intname = 'Корректировка выплат' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_SalaryIn')
update z_datasets set intname = 'tab_CorCR' where intname = 'Корректировка начислений и удержаний' and dscode in (select dscode from z_Datasets s join z_Docs d on s.DocCode = d.DocCode and formclass = 'Tfp_SalaryIn')
