CREATE TABLE [dbo].[r_CRMO] (
  [CRID] [smallint] NOT NULL,
  [OperID] [int] NOT NULL,
  [CROperID] [tinyint] NOT NULL,
  CONSTRAINT [pk_r_CRMO] PRIMARY KEY CLUSTERED ([CRID], [OperID], [CROperID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[r_CRMO]
  ADD CONSTRAINT [FK_r_CRMO_r_CRs] FOREIGN KEY ([CRID]) REFERENCES [dbo].[r_CRs] ([CRID]) ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[r_CRMO]
  ADD CONSTRAINT [FK_r_CRMO_r_OperCRs] FOREIGN KEY ([CRID], [OperID]) REFERENCES [dbo].[r_OperCRs] ([CRID], [OperID]) ON DELETE CASCADE ON UPDATE CASCADE
GO