SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE  FUNCTION [dbo].[pf_GetIntEmpID](@EmpID INT, @OurID INT)/* Возвращает табельный номер сотрудника */RETURNS VARCHAR(50)BEGIN  RETURN ISNULL((SELECT IntEmpID FROM r_EmpMO WHERE OurID = @OurID AND EmpID = @EmpID), ISNULL((SELECT MAX(CAST(IntEmpID AS int)) + 1 FROM r_EmpMO WHERE OurID = @OurID) , 1))END
GO