SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[zf_Base64Decode](@Input NVARCHAR(MAX))
RETURNS VARCHAR(MAX)
BEGIN
  RETURN CAST(CAST(N'' AS XML).value('xs:base64Binary(sql:variable("@Input"))', 'VARBINARY(MAX)') AS VARCHAR(MAX))
END
GO