CREATE TABLE [dbo].[r_CRDeskG]
(
[DeskGCode] [int] NOT NULL,
[WPID] [int] NOT NULL DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[r_CRDeskG] ADD CONSTRAINT [pk_r_CRDeskG] PRIMARY KEY CLUSTERED ([WPID], [DeskGCode]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[r_CRDeskG] ADD CONSTRAINT [FK_r_CRDeskG_r_DeskG] FOREIGN KEY ([DeskGCode]) REFERENCES [dbo].[r_DeskG] ([DeskGCode]) ON DELETE CASCADE ON UPDATE CASCADE
GO
