CREATE TABLE [dbo].[b_PCost]
(
[ChID] [bigint] NOT NULL,
[DocID] [bigint] NOT NULL,
[IntDocID] [varchar] (50) NULL,
[DocDate] [smalldatetime] NOT NULL,
[OurID] [int] NOT NULL,
[CompID] [int] NOT NULL,
[StockID] [int] NOT NULL,
[CodeID1] [smallint] NOT NULL,
[CodeID2] [smallint] NOT NULL,
[CodeID3] [smallint] NOT NULL,
[CodeID4] [smallint] NOT NULL,
[CodeID5] [smallint] NOT NULL,
[CurrID] [smallint] NOT NULL,
[KursAC] [numeric] (21, 9) NOT NULL,
[KursMC] [numeric] (21, 9) NOT NULL,
[KursCC] [numeric] (21, 9) NOT NULL,
[EmpID] [int] NOT NULL,
[Notes] [varchar] (200) NULL,
[StateCode] [int] NOT NULL,
[TNewSumCC_nt] [numeric] (21, 9) NOT NULL,
[TNewSumCC_wt] [numeric] (21, 9) NOT NULL,
[TNewTaxSum] [numeric] (21, 9) NOT NULL,
[GPosID] [int] NOT NULL,
[GTAccID] [int] NOT NULL,
[GTSum_wt] [numeric] (21, 9) NOT NULL,
[GTTaxSum] [numeric] (21, 9) NOT NULL,
[GTCorrSum_wt] [numeric] (21, 9) NOT NULL,
[GTCorrTaxSum] [numeric] (21, 9) NOT NULL,
[GTAdvAccID] [int] NOT NULL,
[GTAdvSum_wt] [numeric] (21, 9) NOT NULL,
[GTCorrAdvSum_wt] [numeric] (21, 9) NOT NULL,
[GTAdvTaxSum] [numeric] (21, 9) NOT NULL,
[GTCorrAdvTaxSum] [numeric] (21, 9) NOT NULL,
[TExpCostCC] [numeric] (21, 9) NOT NULL,
[TExpPosProdCostCC] [numeric] (21, 9) NOT NULL,
[TExpPosCostCC] [numeric] (21, 9) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[b_PCost] ADD CONSTRAINT [pk_b_PCost] PRIMARY KEY CLUSTERED ([ChID]) ON [PRIMARY]
GO
