INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (0, 0, 'Зарезервированный счет', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (1, 0, 'Арендованные необоротные активы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (2, 0, 'Активы на ответственном хранении', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (3, 0, 'Контрактные обязательства', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (4, 0, 'Непредусмотренные активы и обязательства', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (5, 0, 'Гарантии и обеспечения предоставленные', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (6, 0, 'Гарантии и обеспечения полученные', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (7, 0, 'Списанные активы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (8, 0, 'Бланки строгого учета', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (9, 0, 'Амортизационные отчисления', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (10, 1, 'Основные средства', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (11, 1, 'Другие необоротные материальные активы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (12, 1, 'Нематериальные активы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (13, 1, 'Износ (амортизация) необоротных активов', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (14, 1, 'Долгосрочные финансовые инвестиции', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (15, 1, 'Капитальные инвестиции', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (16, 1, 'Долгосрочные биологические активы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (17, 1, 'Отсроченные налоговые активы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (18, 1, 'Долгосрочная дебиторская задолженность и прочие необоротные активы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (19, 1, 'Гудвилл', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (20, 2, 'Производственные запасы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (21, 2, 'Текущие биологичесие активы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (22, 2, 'Малоценные и быстроизнашивающиеся предметы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (23, 2, 'Производство', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (24, 2, 'Брак в производстве', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (25, 2, 'Полуфабрикаты', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (26, 2, 'Готовая продукция', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (27, 2, 'Продукция сельскохозяйственного производства', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (28, 2, 'Товары', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (30, 3, 'Касса', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (31, 3, 'Счета в банках', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (33, 3, 'Другие денежные средства', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (34, 3, 'Краткосрочные векселя полученные', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (35, 3, 'Текущие финансовые инвестиции', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (36, 3, 'Расчеты с покупателями и заказчиками', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (37, 3, 'Расчеты с разными дебиторами', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (38, 3, 'Резерв сомнительных долгов', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (39, 3, 'Расходы будущих периодов', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (40, 4, 'Уставный капитал', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (41, 4, 'Паевой капитал', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (42, 4, 'Дополнительный капитал', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (43, 4, 'Резервный капитал', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (44, 4, 'Нераспределенные прибыли (непокрытые убытки)', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (45, 4, 'Изъятый капитал', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (46, 4, 'Неоплаченный капитал', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (47, 4, 'Обеспечение будущих расходов и платежей', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (48, 4, 'Целевое финансирование и целевые поступления', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (49, 4, 'Страховые резервы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (50, 5, 'Долгосрочные займы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (51, 5, 'Долгосрочные векселя выданные', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (52, 5, 'Долгосрочные обязательства по облигациям', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (53, 5, 'Долгосрочные обязательства по аренде', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (54, 5, 'Отсроченные налоговые обязательства', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (55, 5, 'Другие долгосрочные обязательства', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (60, 6, 'Краткосрочные займы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (61, 6, 'Текущая задолженность по долгосрочным обязательствам', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (62, 6, 'Краткосрочные векселя выданные', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (63, 6, 'Расчеты с поставщиками и подрядчиками', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (64, 6, 'Расчеты по налогам и платежам', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (65, 6, 'Расчеты по страхованию', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (66, 6, 'Расчеты по оплате труда', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (67, 6, 'Расчеты с участниками', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (68, 6, 'Расчеты по другим операциям', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (69, 6, 'Доходы будущих периодов', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (70, 7, 'Доходы от реализации', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (71, 7, 'Другой операционный доход', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (72, 7, 'Доход от участия в капитале', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (73, 7, 'Другие финансовые доходы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (74, 7, 'Прочие доходы (74)', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (75, 7, 'Чрезвычайные доходы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (76, 7, 'Страховые платежи', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (79, 7, 'Финансовые результаты', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (80, 8, 'Материальные затраты', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (81, 8, 'Затраты на оплату труда', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (82, 8, 'Отчисления на социальные мероприятия', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (83, 8, 'Амортизация', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (84, 8, 'Другие операционные затраты', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (85, 8, 'Прочие затраты (85)', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (90, 9, 'Себестоимость реализации', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (91, 9, 'Общепроизводственные расходы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (92, 9, 'Административные расходы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (93, 9, 'Расходы на сбыт', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (94, 9, 'Другие расходы операционной деятельности', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (95, 9, 'Финансовые расходы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (96, 9, 'Потери от участия в капитале', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (97, 9, 'Другие расходы (97)', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (98, 9, 'Налоги на прибыль', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (99, 9, 'Чрезвычайные расходы', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (101, 10, 'Валовый доход от всех видов деятельности', 'код строки 01');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (102, 10, 'Учет балансовой стоимости для налогового учета', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (103, 10, 'Валовые расходы, в том числе', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (104, 10, 'Дополнительные показатели', '');
INSERT dbo.r_GAccs2(GAccID2, GAccID1, GAccName2, Notes) VALUES (105, 10, 'Уменьшение начисленной суммы налога', 'Код строки 13 (К6)');
