INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10101, 'Добавление в справочник', '10101', 1, 'Справочники', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10106, 'Выбор из справочника', 'Tfz_RefSelect', 0, 'Справочники', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10107, 'Поиск в справочнике', 'Tfz_RefFindPrompt', 0, 'Справочники', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10201, 'Изменить статус документа', '10201', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10211, 'Идентификация служащего', '10211', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10501, 'Мастер копирования', 'Tfs_WCopyE', 1, 'Мастер', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10601, 'Монитор документа', 'Tfz_MonitorDoc', 0, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10602, 'Выбор связанного документа', 'Tfz_DocLinks', 0, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10801, 'Уведомления', 'Tfz_Notify', 0, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10901, 'Импорт', '10901', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10902, 'Импорт из текстового файла', '10902', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10911, 'Экспорт', '10911', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10912, 'Экспорт в текстовый файл', '10912', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10914, 'Экспорт печатных форм', '10914', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10915, 'Экспорт в Excel', '10915', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10951, 'Прочие инструменты: Приложение', 'ToolApp', 0, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10952, 'Прочие инструменты: SQL-запрос', 'ToolSQL', 0, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (10953, 'Прочие инструменты: Fast Report', 'ToolFastReport', 0, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11011, 'Операции с чеком', '11011', 0, 'Прикладные', 'ALT + Q');
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11012, 'Операции с кассой', '11012', 0, 'Прикладные', 'ALT + W');
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11013, 'Кассовые отчеты', '11013', 0, 'Прикладные', 'ALT + E');
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11014, 'Главные операции Торгового клиента', '11014', 0, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11099, 'Запуск Торгового клиента', '11099', 0, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11100, 'Завершение работы Торгового клиента', '11100', 0, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11101, 'Создать новый товар', '11101', 1, 'Справочники', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11106, 'Проводник по товарам', 'Tft_ProdExplorer', 0, 'Справочники', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11107, 'Поиск товара', 'Tft_ProdFind', 0, 'Справочники', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11108, 'Подбор товара по каталогу', 'Tfz_ProdSelect', 0, 'Справочники', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11111, 'Сортировка товаров', '11111', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11151, 'Рассчитать себестоимость', '11151', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11201, 'Дисконтные карты', '11201', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11202, 'Скидки на позицию', '11202', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11301, 'Изменить цены прайс-листов', '11301', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11311, 'Автораспределение товара', '11311', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11312, 'Автораспределение количества', '11312', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11321, 'Формирование себестоимости', '11321', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11322, 'Изменить процент наценки', '11322', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11331, 'Чек на текущий ЭККА', '11331', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11341, 'Рассчитать всю инвентаризацию', '11341', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11342, 'Рассчитать инвентаризацию текущей позиции', '11342', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11351, 'Рассчитать параметры распределения', '11351', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11361, 'Рассчитать по весу составляющих', '11361', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11362, 'Заполнить отсутствующими товарами', '11362', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11501, 'Мастер прайс-листов', '11501', 1, 'Мастер', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11511, 'Мастер повторного списания', 'Tfz_WAutoPP', 1, 'Мастер', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11512, 'Мастер переоценки партий', '11512', 1, 'Мастер', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11521, 'Мастер внешних заказов', '11521', 1, 'Мастер', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11531, 'Мастер автоформирования комплектов', '11531', 1, 'Мастер', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11541, 'Мастер программирования весов', '11541', 1, 'Мастер', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11611, 'Монитор товара', 'Tft_MonitorProd', 0, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11612, 'Монитор сертификатов', 'Tft_MonitorImages', 0, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11614, 'Монитор заказа', 'Tft_MonitorOrd', 0, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11615, 'Монитор наценки', 'Tft_MonitorExtra', 0, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11616, 'Монитор переоценки', 'Tft_MonitorEst', 0, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11621, 'Монитор возврата', 'Tft_MonitorRet', 0, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11901, 'Создать налоговую накладную', '11901', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11902, 'Выбрать номер налоговой накладной', '11902', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (11903, 'Удалить налоговую накладную', '11903', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14101, 'Изменить групповую операцию', '14101', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14111, 'Очередность документов ', '14111', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14112, 'Восстановить очередность документов', '14112', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14115, 'Рассчитать сальдо и проводки', '14115', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14116, 'Рассчитать сальдо по строкам документа', '14116', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14201, 'Изменить цену прихода…', '14201', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14501, 'Мастер восстановления проводок', '14501', 1, 'Мастер', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14511, 'Мастер основных средств', '14511', 1, 'Мастер', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14601, 'Монитор проводок', 'Tfb_MonitorTran', 0, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14611, 'Монитор ТМЦ', 'Tfb_MonitorProd', 0, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (14621, 'Монитор возврата ТМЦ', 'Tfb_MonitorRet', 0, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15201, 'Заполнить служащими и рассчитать', '15201', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15202, 'Заполнить служащими', '15202', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15211, 'Рассчитать начисления для текущего служащего', '15211', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15221, 'Рассчитать табель для всех служащих', '15221', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15222, 'Рассчитать табель для текущего служащего', '15222', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15241, 'Рассчитать выплату', '15241', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15301, 'Рассчитать коммунальный налог', '15301', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15311, 'Рассчитать средний заработок', '15311', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15321, 'Рассчитать корректировку для всех служащих', '15321', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15331, 'Рассчитать корректировку по служащему', '15331', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15341, 'Рассчитать отпуск по периодам', '15341', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15351, 'Рассчитать по кадровому состоянию', '15351', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15611, 'Подробно по служащему', '15611', 1, 'Монитор', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (15901, 'Экспорт данных персонификации', '15901', 1, 'Прикладные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (37101, 'Создать триггера репликации', '37101', 1, 'Служебные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (37102, 'Создать процедуры репликации', '37102', 1, 'Служебные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (40101, 'Создать процедуры дисконтной системы', '40101', 1, 'Служебные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (50101, 'Восстановить ссылочную целостность', '50101', 1, 'Служебные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (50121, 'Восстановить автоизменение', '50121', 1, 'Служебные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (50122, 'Создать процедуры автоизменения', '50122', 1, 'Служебные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (50201, 'Экспорт конфигурации', '50201', 1, 'Служебные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (50202, 'Импорт конфигурации', '50202', 1, 'Служебные', NULL);
INSERT dbo.z_ToolRep(RepToolCode, RepToolName, FormClass, IsInt, RepToolCatName, ShortCut) VALUES (50203, 'Установка пакета обновления', '50203', 1, 'Служебные', NULL);
