INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (0, 0, 'Общая категория групповых операций', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (1, 1, 'Кассовые, банковские операции', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (2, 2, 'Расчеты с подотчетными лицами', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (3, 3, 'Расчеты с поставщиками', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (4, 4, 'Расчеты с покупателями и заказчиками (оптовая торговля)', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (5, 5, 'Расчеты с покупателями и заказчиками (розничная торговля)', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (6, 6, 'Переоценка ТМЦ', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (7, 7, 'Расчеты по заработной плате', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (10, 10, 'Необоротные активы', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (13, 13, 'Учет расчетов с учредителями', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (14, 14, 'Капитал, превышающий уставный', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (17, 17, 'Инвентаризация', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (18, 18, 'Учет краткосрочных кредитов банков', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (19, 19, 'Учет долгосрочных кредитов банков', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (20, 20, 'Покупка иностранной валюты', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (21, 21, 'Продажа иностранной валюты', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (23, 23, 'Вексельное обращение', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (25, 25, 'Начисление и оплата налогов и сборов', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (26, 26, 'Закрытие финансового результата', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (27, 27, 'Складские операции', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (28, 28, 'Суммовой учет товаров', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (29, 29, 'Арендные операции', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (30, 30, 'Ввод остатков', '');
INSERT dbo.r_GOperC(GOperCID, ChID, GOperCName, Notes) VALUES (31, 31, 'Кадры и Зарплата', '');
