INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10011, 0, 'Не указан', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10011, 1, 'Мужской', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10011, 2, 'Женский', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 0, 'Нет типа гражданско-правового договора', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 1, 'Договор поставки', 'Договiр поставки');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 2, 'Договор купли-продажи', 'Договiр купiвлi-продажу');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 3, 'Договор консигнации', 'Договiр консигнацiї');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 4, 'Договор комиссии', 'Договiр комiсiї');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 5, 'Договор поручительства', 'Договiр поруки');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 6, 'Договор поручения', 'Договiр доручення');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 7, 'Договор доверительного управления', 'Договiр довiрчого управлiння');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 8, 'Договор ответственного хранения', 'Договiр вiдповiдального зберiгання');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 9, 'Договор складского хранения', 'Договiр складського зберiгання');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 10, 'Договор о предоставлении посреднических услуг', 'Договiр про надання посередницьких послуг');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 11, 'Договор о выполнении работ', 'Договiр про виконання роботи');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 12, 'Договор о предоставлении услуг', 'Договiр про надання послуг');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 13, 'Договор об информационно-справочном обслуживании', 'Договір про інформаційно-довідкове обслуговування');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 14, 'Договор поставки оптовой партии', 'Договiр поставки оптової партiї');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 15, 'Договор аренды', 'Договiр оренди');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 16, 'Договор подряда', 'Договiр пiдряду');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10020, 17, 'Договор перевозки', 'Договiр перевезення');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 0, 'Прочее', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 1, 'Налоговая накладная', 'ПН');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 2, 'Корректировка (Приложение 1)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 3, 'Корректировка (Приложение 2)', 'РК');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 4, 'ГТД', 'ВМД');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 5, 'Товарный/кассовый чек (вх.)', 'ЧК');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 6, 'Транспортный билет (вх.)', 'ТК');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 7, 'Гостиничный счет (вх.)', 'ГР');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 8, 'Счет за услуги связи (вх.)', 'ПЗ');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 9, 'Стоимость по приборам учета (вх.)', 'ПО');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 10, 'Заявление плательщика (вх.)', 'ЗП');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 11, 'Ежедневные итоги (исх.)', 'ПН11');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 12, 'Превышение цены (исх.)', 'ПН01');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 13, 'Поставка неплательщику НДС (исх.)', 'ПН02');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 14, 'Натуральная оплата в счет зарплаты (исх.)', 'ПН03');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 15, 'В рамках баланса не для производства (исх.)', 'ПН04');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 16, 'Ликвидация ОС (исх.)', 'ПН05');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 17, 'Перевод ОС в непроизводственные фонды (исх.)', 'ПН06');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 18, 'Экспорт (исх.)', 'ПН07');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 19, 'Не объекты НДС (исх.)', 'ПН08');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 20, 'Особождены от НДС (исх.)', 'ПН09');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10041, 21, 'Условная поставка плательщика при аннулировании регестрации (исх.)', 'ПН10');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10042, 0, 'Причина не указана (не корректировка)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10042, 1, 'Изменение суммы компенсации стоимости товаров (услуг) после их поставки, включая пересмотр цен', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10042, 2, 'Возврат товаров', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10042, 3, 'Возврат поставщиком суммы предоплаты', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10050, 0, 'Не определен', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10050, 1, 'Работники основного производства', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10050, 2, 'Работники аппарата управления цехами', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10050, 3, 'Работники административно-управленческого аппарата', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10050, 4, 'Работники отдела сбыта', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10050, 5, 'Работники, занятые исследованиями и разработками', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10050, 6, 'Работники социально-культурной сферы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 11, 'Ежегодный основной отпуск', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 12, 'Дополнительный отпуск за работу с вредными и тяжелыми условиями труда', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 13, 'Дополнительный отпуск за особый характер труда', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 14, 'Дополнительный отпуск (донор)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 21, 'Дополнительный отпуск в связи с обучением', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 31, 'Творческий отпуск', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 41, 'Социальный отпуск для ухода за ребенком до трех лет', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 42, 'Отпуск без сохранения заработной платы для ухода за ребенком до шести лет', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 43, 'Дополнительный отпуск (как одинокой матери)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 44, 'Дополнительный отпуск (как женщине, имеющей ребенка-инвалида)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 45, 'Дополнительный отпуск (как женщине, имеющей двоих детей в возрасте до 15 лет)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 46, 'Дополнительный отпуск (как женщине, которая усыновила ребенка)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 47, 'Дополнительный отпуск (гражданам, пострадавшим вследствие Чернобыльской катастрофы)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 51, 'Отпуск без сохранения заработной платы (по семейным обстоятельствам)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 52, 'Отпуск без сохранения заработной платы (как пенсионеру по возрасту)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 53, 'Отпуск без сохранения заработной платы (как инвалиду 3 группы)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 54, 'Отпуск без сохранения заработной платы (как инвалиду 1 или 2 группы)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 55, 'Отпуск без сохранения заработной платы (для ухода за больным родственником)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 56, 'Отпуск без сохранения заработной платы (в связи с вступлением в брак)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 57, 'Отпуск без сохранения заработной платы (мужу, жена которого находится в послеродовом отпуске)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 58, 'Отпуск без сохранения заработной платы (в связи со смертью родных по крови или по браку)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 59, 'Отпуск без сохранения заработной платы (в связи c обучением)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 61, 'Военные сборы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 71, 'Мобилизация', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 1011, 'Основной отпуск', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 1012, 'Дополнительный отпуск за работу с вредными и тяжёлыми условиями труда', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 1014, 'Другие дополнительные отпуска, предусмотренные законодательством', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 1021, 'Дополнительный отпуск в связи с учебой', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 1041, 'Отпуск в связи с беременностью и родами', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 1042, 'Отпуск по уходу за ребенком до трех лет', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 1043, 'Отпуск по уходу за ребенком до шести лет', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 1044, 'Дополнительный отпуск работникам, имеющим детей', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 1051, 'Отпуск без сохранения заработной платы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10051, 10000, 'Компенсация отпуска', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 280, 'По результатам испытания', 'по результатам испытания в связи с несоответсвием работника работе, на которую он принят, ст. 28 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 361, 'По соглашению сторон', 'по соглашению сторон, п. 1 ст. 36 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 362, 'Истечение срока договора', 'в связи с истечением срока действия трудового договора, п. 2 ст. 36 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 363, 'Призыв на воинскую службу', 'в связи с призывом или поступлением работника на воинскую службу, п. 3 ст. 36 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 365, 'Перевод', 'в связи с переводом, п. 5 ст. 36 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 366, 'Отказ от перевода вместе с предприятием', 'в связи с отказом от перевода на работу в другую местность вместе с предприятием, п. 6 ст. 36 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 367, 'Вступление в силу приговора суда', 'в связи со вступлением в силу приговора суда, п. 7 ст. 36 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 368, 'Основание, предусмотренное контрактом', 'по условиям контракта, п. 8 ст. 36 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 370, 'Направление на принудительное лечение', 'в связи с направлением по постановлению суда на принудительное лечение, ст. 37 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 380, 'По собственному желанию', 'по собственному желанию, ст. 38 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 381, 'По собственному желанию (переезд на новое место жительства)', 'по собственному желанию в связи с переездом на новое место жительства, ст. 38 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 382, 'По собственному желанию (перевод супруга на работу в другую местность)', 'по собственному желанию в связи с переводом мужа или жены на работу в другую местность, ст. 38 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 383, 'По собственному желанию (поступление в учебное заведение)', 'по собственному желанию в связи с поступлением в учебное заведение, ст. 38 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 384, 'По собственному желанию (невозможность проживать в данной местности)', 'по собственному желанию в связи с невозможностью проживания в данной местности, ст. 38 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 385, 'По собственному желанию (беременность)', 'по собственному желанию в связи с беременностью, ст. 38 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 386, 'По собственному желанию (по уходу за ребенком до 14 лет)', 'по собственному желанию по уходу за ребенком до достижения им четырнадцатилетнего возраста или ребенком-инвалидом, ст. 38 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 387, 'По собственному желанию (по уходу за больным)', 'по собственному желанию по уходу за больным членом семьи или инвалидом I группы, ст. 38 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 388, 'По собственному желанию (выход на пенсию)', 'по собственному желанию в связи с выходом на пенсию, ст. 38 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 389, 'По собственному желанию (прием на работу по конкурсу)', 'по собственному желанию в связи с приемом на работу по конкурсу, ст. 38 КЗоТ Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 401, 'Изменение организации производства и труда', 'в связи с изменением организации производства и труда, п. 1 ст. 40 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 402, 'Несоответствие занимаемой должности', 'в связи с несоответствием работника занимаемой должности или выполняемой работе, п. 2 ст. 40 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 403, 'Невыполнение обязанностей', 'в связи с систематическим невыполнением работником без уважительных причин обязанностей, п. 3 ст. 40 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 404, 'Прогул', 'в связи с прогулом без уважительной причины, п. 4 ст. 40 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 405, 'Неявка более четырех месяцев', 'в связи с неявкой на работу в течение более четырех месяцев подряд вследствие временной нетрудоспособности, п. 5 ст. 40 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 406, 'Восстановление работника, ранее выполнявшего эту работу', 'в связи с восстановлением на работе работника, ранее выполнявшего эту работу, п. 6 ст. 40 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 407, 'Появление в нетрезвом виде', 'в связи с появлением на работе в нетрезвом состоянии, в состоянии наркотического или токсического опьянения, п. 7 ст. 40 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 408, 'Совершение хищения', 'в связи с совершением по месту работы хищения имущества собственника, п. 8 ст. 40 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 411, 'Грубое нарушение трудовых обязанностей руководителем', 'в связи с грубым нарушением трудовых обязанностей, п. 1 ст. 41 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 412, 'Утрата доверия', 'в связи с виновными действиями работника, дающими основания для утраты доверия к нему, п. 2 ст. 41 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 413, 'Аморальный проступок воспитателя', 'в связи с совершением работником аморального проступка, не совместимого с продолжением данной работы, п. 3 ст. 41 КЗот Украины');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10055, 10000, 'Смерть', 'в связи со смертью');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 1, 'Общее заболевание', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 2, 'Профессиональное заболевание и его последствия', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 3, 'Последствия аварии на ЧАЭС', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 4, 'Несчастный случай на производстве и его последствия', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 5, 'Непроизводственные травмы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 6, 'Контакт с больными инфекционными заболеваниями и бактерионосительство', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 7, 'Санаторно-курортное лечение', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 8, 'Беременность и роды', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 9, 'Ортопедическое протезирование', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 10, 'Уход', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10056, 99, 'Прочее', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 1, 'Наемные работники на общих основаниях', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 2, 'Работающие инвалиды', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 6, 'Для ФЛ - плательщиков фиксированного налога', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 8, 'Для ФЛ - плательщиков единого налога', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 9, 'Член семьи ФЛ-СПД на общих условиях', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 10, 'Член семьи ФЛ-СПД на особых условиях', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 11, 'Лица, страхующиеся добровольно по договору', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 12, 'Лица, доплачивающие страховые взносы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 13, 'Лица, обеспечивающие себя работой самостоятельно', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 14, 'ФЛ-СПД на общих условиях (%)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 15, 'Члены КСП, кооперативов (%)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 16, 'Лица, проходящие срочную военную службу', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 17, 'Лица, получающие помощь по уходу за ребенком', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 18, 'Лицо, ухаживающее за инвалидом или престарелым', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 19, 'Родители-воспитатели, приемные родители', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 20, 'Для ФЛ-плательщиков фиксированного налога, доплачивающих страховые взносы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 21, 'Для ФЛ-плательщиков единого налога, доплачивающих страховые взносы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 22, 'Член семьи ФЛ на особых условиях - фиксированный налог, за которого доплачивают страховые взносы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10057, 23, 'Член семьи ФЛ на особых условиях - единый налог, за которого доплачивают страховые взносы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 1, 'Наемный работник на общих основаниях', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 2, 'Работающий инвалид', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 3, 'Лицо летного состава', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 4, 'Член КСП, с/х кооператива', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 5, 'ФЛ-СПД на общих условиях', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 6, 'ФЛ-СПД на особых условиях', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 7, 'Член семьи ФЛ-СПД на общих условиях', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 8, 'Член семьи ФЛ-СПД на особых условиях', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 9, 'Лицо, получающее доход от независимой профессиональной деятельности', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 10, 'Гражданин Украины, работающий за границей', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 11, 'Работник иностранных организаций в Украине', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 12, 'Лицо на выборной должности', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 13, 'Работник военизированных формирований', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 14, 'Лицо на альтернативной службе', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 15, 'Лицо, обучающееся с отрывом от производства', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 16, 'Лицо, страхующееся добровольно', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 17, 'Лицо, доплачивающее страховые взносы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 18, 'Лицо, проходящее срочную военную службу', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 19, 'Лицо, получающее страховые выплаты ФСНС', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 20, 'Лицо, получающее помощь по уходу за ребенком', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 21, 'Лицо, ухаживающее за инвалидом или престарелым', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 22, 'Лицо, получающее помощь по безработице', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 23, 'Военнослужащий без права на пенсию за выслугу лет', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 24, 'Родители-воспитатели', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 25, 'Наемные работники, работающие на должностях, работа на которых засчитывается в стаж, дающий право на получение пенсии в соответствии с отдельными законами Украины', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 26, 'Для лиц, работающих при ГПХ', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 27, 'Лица, работающие на предприятиях и организациях всеукраинских общественных организаций', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 28, 'Работающий инвалид на предприятии или организации общественных организаций инвалидов, в которых количество инвалидов более 50%', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 29, 'Лица, получающие пособие по временной нетрудоспособности', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 30, 'Наемный работник - инвалид, работающий на предприятиях и организациях всеукраинских общественных организаций инвалидов, в частности обществах УТОГ и УТОС', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 31, 'Военнослужащие, лица рядового и начальствующего состава', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 32, 'Работающий инвалид (32)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 33, 'Лицо, которое ухаживает за инвалидом I группы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 34, 'Лицо, которое ухаживает за престарелым', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 35, 'ФЛ-СПД на ОСН, которое доплачивает единый взнос', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 36, 'Работающий инвалид (36)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 37, 'Лица, работающие на предприятиях и в организациях всеукраинских общественных организаций инвалидов, в частности обществах УТОГ и УТОС (37)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 38, 'Лица, работающие на предприятиях и в организациях всеукраинских общественных организаций инвалидов, в частности обществах УТОГ и УТОС (38)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 39, 'Работающий инвалид на предприятии или в организации общественных организаций инвалидов, в которых количество инвалидов составляет более 50% (39)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 40, 'ФЛ - предприниматели, которые увеличивают или уменьшают суммы обязательств по страховым взносам по результатам проведенной проверки (сверки)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 41, 'Наемный работник - инвалид, работающий на предприятиях и в организациях всеукраинских общественных организаций инвалидов', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 42, 'Лица, получающие пособие по беременности и родам', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 43, 'Работающие лица - инвалиды, получающие пособие по беременности и родам', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 44, 'Лица, находящиеся в отпуске по беременности и родам и получают помощь в связи с беременностью и родами, работающих на предприятиях и в организациях всеукраинских общественных организаций инвалидов, в частности обществах УТОГ и УТОС', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 45, 'Работающие лица - инвалиды, находящиеся в отпуске по беременности и родам и получают помощь в связи с беременностью и родами, которые работают на предприятии или в организации общественных организаций инвалидов, в которых количество инвалидов составляет более 50%', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 46, 'Лицо, работающее у физического лица на условиях трудового договора (контракта)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 47, 'Наемный работник', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 48, 'Работник, призванный на срочную военную службу, военную службу по призыву по мобилизации, на особый период или принят на военную службу по контракту', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10058, 49, 'Наемный работник в зоне антитеррористической операции, которому предоставлен отпуск без сохранения заработной платы', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10059, 0, 'Нет корректировки', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10059, 1, 'Продление', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10059, 2, 'Перенос', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10059, 3, 'Отзыв', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10059, 4, 'Выход', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10060, 0, 'Причина не указана', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10060, 1, 'Временная нетрудоспособность', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10060, 2, 'Учебный отпуск', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10060, 3, 'Производственная необходимость', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10060, 4, 'Выход из декретного отпуска', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10060, 5, 'Выход в декретном отпуске', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 0, 'Не указано', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 1, 'Базовое общее среднее', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 2, 'Полное общее среднее', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 3, 'Профессионально-техническое', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 4, 'Неполное высшее', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 5, 'Базовое высшее', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 6, 'Полное высшее', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 1001, 'Начальное (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 1002, 'Неполное среднее (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 1003, 'Среднее (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 1004, 'Среднее специальное (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 1005, 'Неполное высшее (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10061, 1006, 'Высшее (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 0, 'Не указано', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 1, 'Женат/замужем - состоит в зарегистрированном браке', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 2, 'Холост/не замужем - никогда не состоял(а) в браке', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 3, 'Разведен/разведена', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 4, 'Вдовец/вдова', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 5, 'Состоит в незарегистрированном браке', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 1000, 'Женат - состоит в зарегистрированном браке (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 1001, 'Замужем - состоит в зарегистрированном браке (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 1002, 'Холост - никогда не состоял в браке (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 1003, 'Не замужем - никогда не состояла в браке (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 1004, 'Разведен (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 1005, 'Разведена (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 1006, 'Вдова (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10062, 1007, 'Вдовец (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10063, 0, 'Не указано', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10063, 1, 'Допризывник', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10063, 2, 'Призывник', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10063, 3, 'Военнообязанный', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10063, 4, 'Военнослужащий', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10063, 5, 'Резервист', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10063, 1000, 'Не военнообязанный (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10063, 1005, 'Служащие по призыву (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10064, 0, 'Не указано', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10064, 1, 'Ограниченно годен', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10064, 2, 'Годен', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10064, 1000, 'Не годен (недействительное)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 0, 'Нет действия', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 1, 'Штрихкод товара', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 2, 'Код товара', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 3, 'Подбор товара по каталогу', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 4, 'DataMatrix товара (код маркировки)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 11, 'Дисконтная карта', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 12, 'Поиск дисконтной карты', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 13, 'Абонемент', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 14, 'Номер телефона', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 41, 'Акцизная марка', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 51, 'Штрихкод служащего', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 61, 'Идентификация клиента', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 71, 'QR Код (идентификация через приложение)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10455, 72, 'QR код с обработкой через t_SaleOnEvent', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10606, 0, 'Не указана', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10606, 1, 'Администратор', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10606, 2, 'Бармен', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10606, 3, 'Официант', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10606, 4, 'Повар', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10607, 0, 'Не указана', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10607, 1, 'Ошибка официанта', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10607, 2, 'Отказ клиента', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10607, 3, 'Прочее', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10608, 0, 'Нет типа изображения', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10608, 1, 'Товар', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10608, 2, 'Сертификат', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10609, 0, 'Вид документа не указан', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10609, 1, 'ИНН', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10609, 2, 'Паспорт', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10609, 3, 'Диплом', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10609, 4, 'Справка', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10609, 5, 'Заявление', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10609, 6, 'Анкета', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10609, 7, 'Резюме', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 0, 'Без опыта', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 1, '1С', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 2, 'Украинский язык', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 3, 'Английский язык', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 4, 'Личный автомобиль', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 5, 'Переговоры', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 6, 'Управленец', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 7, 'Исполнитель', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 8, 'Загранпаспорт', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 9, 'Управленческий учет', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 10, 'Прямые/активные продажи', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10610, 11, 'Возможность переезда', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10611, 0, 'Нет статуса', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10611, 1, 'VIP', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10611, 2, 'ТОП', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10611, 3, 'Студенты', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10611, 4, 'Начало карьеры', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10611, 5, 'Аутсорсинг', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10611, 6, 'Freelance', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10612, 0, 'Кандидату отказано', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10612, 1, 'Кандидату отказано (прием под ответственность ГМ)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10612, 2, 'Кандидат согласован', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10612, 3, 'Кандидат согласован (на усмотрение непосредственного руководителя)', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10701, 0, 'Нет статуса', '');
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10702, 0, 'Не указана', NULL);
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10702, 1, 'Ошибка кассира', NULL);
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10800, 0, 'Вручную', NULL);
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10800, 1, 'Сканер', NULL);
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10800, 2, 'Весы', NULL);
INSERT dbo.r_Uni(RefTypeID, RefID, RefName, Notes) VALUES (10800, 3, 'Автоматически расчитано', NULL);
