INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (0, 'Отображение диалогового окна', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (1, 'Добавление товарной позиции', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (2, 'Сохранение товарной позиции', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (3, 'Предоставление позиционной скидки', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (4, 'Отображение окна ввода ДК', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (5, 'Отображение окна посика ДК', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (6, 'Получение информации по ДК', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (7, 'Предоставление скидок по ДК', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (8, 'Удаление ДК из чека', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (9, 'Поиск ДК', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (10, 'Чек отложен', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (11, 'Возврат к отложенному чеку', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (12, 'Получение информации о товарной позиции', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (13, 'Обновление информации о товарной позиции', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (14, 'Отображение окна редактирование позиции', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (15, 'Пересчет параметров позиции после редактирования', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (16, 'Переход в режим продаж', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (17, 'Переход в режим отмены продаж', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (18, 'Проверка баланса между РРО и БД', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (19, 'Отображение окна скидок', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (20, 'Пинг ПЦ (Ping)', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (21, 'Активация карты ПЦ (CardActivate)', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (22, 'Деактивация карты ПЦ (CardDeactivate)', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (23, 'Информация по карте ПЦ (СardInfo)', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (24, 'Операция покупки в ПЦ (BuyNew)', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (25, 'Подтверждение операции ПЦ (BuyCommit)', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (26, 'Отмена операции ПЦ (BuyCancel)', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (27, 'Операция возврата в ПЦ (BuyReturn)', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (28, 'Информация о транзакции в ПЦ (TransactionInfo)', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (29, 'Обработка бонусов ПЦ', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (30, 'Замена карты (SMS)', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (31, 'Обмен карт', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (32, 'Замена/Обмен карт Commit', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (34, 'Отображение баланса кассы', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (40, 'Закрытие чека', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (41, 'Предоставление чековой скидки', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (42, 'Сохранение оплат', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (43, 'Начало печати чека в БПТ', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (44, 'Открытие денежного ящика', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (45, 'Создание заголовка чека продажи', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (46, 'Просмотр ПФ', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (47, 'Печать ПФ', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (48, 'Печать чека на РРО', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (49, 'Загрузка данных чека для печати', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (50, 'Загрузка примечаний к позициям чека', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (51, 'Загрузка примечаний чека', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (52, 'Перенос чека из временной таблицы продаж', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (53, 'Перенос начислений и списаний', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (54, 'Печать копии чека', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (55, 'Проверка статуса РРО', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (56, 'Проверка необходимости выполнения Z-отчета', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (57, 'Подготовка перед диалогом закрытия чека', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (58, 'Печать дополнительного чека', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (59, 'Отмена всего чека', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (60, 'Вывод информации на дисплей РРО', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (61, 'Переподключение к РРО', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (80, 'Отображение окна ''Поиск цены''', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (81, 'Поиск цены', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (82, 'Печать информации о подарочном сертификате', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (83, 'Отображение окна ''Подбор товара по каталогу''', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (84, 'Подбор товара по каталогу', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (85, 'Отображение окна идентификации служащего', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (86, 'Идентификация служащего', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (100, 'Запуск приложения', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (101, 'Завершение работы приложения', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (102, 'Блокировка приложения', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (120, 'X-отчет', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (121, 'Z-отчет', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (122, 'Сокр. отчет за период', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (123, 'Сокр. отчет по номерам', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (124, 'Отчет за период', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (125, 'Отчет по номерам', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (126, 'Отчет по артикулам', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (127, 'Служебный внос', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (128, 'Служебный вынос', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (129, 'Нулевой чек', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (130, 'Копия чека', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (132, 'Создание чека продажи', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (150, 'Сканирование в поле ввода суммы', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (151, 'Ручной ввод', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (1001, 'Разблокировка приложения', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (2001, 'Решение по печати чека РРО/ПРРО', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (2002, 'Выбор причины возврата', 1);
INSERT dbo.z_MetricaEvents(EventID, EventName, Enabled) VALUES (2003, 'Выбор причины отмены', 1);
