INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10011, 1, 'Справочник полов', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10020, 12, 'Справочник типов гражданско-правовых договоров', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10041, 6, 'Справочник видов налоговых накладных', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10042, 13, 'Справочник причин корректировки налоговых накладных', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10050, 2, 'Справочник типов должностей', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10051, 3, 'Справочник типов отпусков', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10055, 4, 'Справочник причин увольнения', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10056, 5, 'Справочник причин нетрудоспособности', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10057, 7, 'Справочник типов ставок страхового сбора', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10058, 8, 'Справочник категорий застрахованных лиц', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10059, 15, 'Справочник типов корректировки отпуска', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10060, 16, 'Справочник причин корректировки отпуска', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10061, 22, 'Справочник видов образования', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10062, 25, 'Справочник видов семейного положения', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10063, 26, 'Справочник категорий воинской обязанности', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10064, 27, 'Справочник видов годности к военной службе', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10455, 11, 'Справочник ЭККА: Единый ввод: Действия', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10606, 9, 'Справочник должностей в смене ресторана', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10607, 10, 'Справочник причин отмены', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10608, 14, 'Справочник типов изображений', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10609, 19, 'Справочник видов документов', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10610, 20, 'Справочник кандидатов: навыки/ресурсы', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10611, 21, 'Справочник кандидатов: статусы', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10612, 23, 'Справочник кандидатов: результат проверки АО', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10701, 17, 'Справочник статусов персон', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10702, 18, 'Справочник причин возврата', NULL);
INSERT dbo.r_UniTypes(RefTypeID, ChID, RefTypeName, Notes) VALUES (10800, 24, 'Справочник способов ввода данных', NULL);
