INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (0, 0, 'Нет статуса', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (11, 11, 'Рассчитана себестоимость', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (12, 12, 'Рассчитана инвентаризация', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (21, 21, 'Документ проведен по бухгалтерии', NULL, 0);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (22, 22, 'Документ распечатан на ЭККА', NULL, 0);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (23, 23, 'Документ распечатан на ЭККА, заказ выдан', NULL, 0);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (110, 110, 'Документ в работе', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (115, 115, 'Документ на согласовании', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (120, 120, 'Документ согласован', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (125, 125, 'Документ на утверждении', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (130, 130, 'Документ утвержден', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (135, 135, 'Документ готов', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (140, 140, 'Документ проведен', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (145, 145, 'Документ закрыт', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (150, 150, 'Документ заблокирован', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (510, 510, 'Товар в резерве', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (515, 515, 'Товар разрешен на отпуск', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (520, 520, 'Товар на погрузке', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (525, 525, 'Товар отпущен', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (530, 530, 'Товар в пути', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (535, 535, 'Товар на границе', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (540, 540, 'Товар на таможне', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (545, 545, 'Товар получен', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (550, 550, 'Товар на разгрузке', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (555, 555, 'Товар разгружен', NULL, 1);
INSERT dbo.r_States(StateCode, ChID, StateName, StateInfo, CanChangeDoc) VALUES (560, 560, 'Товар на складе', NULL, 1);
