
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (0, 0, 'Нет формы оплаты', NULL, NULL, NULL, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (1, 1, 'Готівка', NULL, 'Готівкою', NULL, 0, '', 1, 2, 1, 1, 1, 0, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (2, 2, 'Платіжна картка', NULL, 'Платіжною карткою', 'Номер карты', 0, '9999-****-****-9999', 1, 0, 0, 1, 1, 0, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (3, 100000001, 'Кредит', NULL, 'Кредитом', NULL, 0, '', 1, 1, 0, 0, 0, 0, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (4, 100000002, 'Чек', NULL, 'Чеком', NULL, 0, '', 1, 0, 0, 0, 0, 0, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (5, 100000003, 'Подарунковий сертифікат', NULL, 'Сертифікатом', 'Номер сертифіката', 0, '9999999999999', 0, 0, 0, 0, 0, 10, 2, 1, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (6, 100000004, 'Оплата частями: в периоде', NULL, 'ОЧ: в периоде', 'Кол-во платежей', 1, '!99', 0, 1, 0, 1, 1, 12, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (7, 100000005, 'Оплата частями: стандартная', NULL, 'ОЧ: стандартная', 'Кол-во платежей', 1, '!99', 0, 1, 0, 1, 1, 12, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (8, 100000006, 'Оплата частями: мгновенная рассрочка', NULL, 'ОЧ: мгнов рассрочка', 'Кол-во платежей', 1, '!99', 0, 1, 0, 1, 1, 12, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (9, 100000007, 'Бонусами', NULL, 'Бонусами:', NULL, 0, '', 1, 1, 0, 0, 0, 0, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (10, 100000008, 'Моб.застосунок EasyWallet', NULL, 'Моб.застосунок EasyWallet', NULL, 0, '', 1, 1, 0, 1, 1, 12, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (11, 100000009, 'Карткою с видачей готівки', NULL, 'Карткою', 'Видати готівки', 1, '', 1, 0, 0, 0, 0, 0, 0, 0, NULL);
INSERT dbo.r_PayForms(PayFormCode, ChID, PayFormName, Notes, SumLabel, NotesLabel, CanEnterNotes, NotesMask, CanEnterSum, MaxQty, IsDefault, ForSale, ForRet, AutoCalcSum, DCTypeGCode, GroupPays, CRPayTypeCode) VALUES (12, 100000010, 'Безготівкова', NULL, 'Безготівкова', NULL, 0, '', 1, 1, 0, 0, 0, 0, 0, 0, NULL);
