INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (1, 'НЗ_ЗК_МаксОблагаемаяСумма', 'Используется для вычисления максимально налого-облагаеммой суммы', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (10, 'НЗ_ЗК_УдержаниеПодоходногоНалога', 'Используется для расчета подоходного налога в приложении кадры и зарплата', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (11, 'НЗ_ЗК_УдержаниеВПенсионныйФонд', 'Используется для вычисления суммы пенсионного фонда при начислении зарплаты', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (12, 'НЗ_ЗК_УдаржаниеВФондБезработицы', 'Используется для вычисления суммы фонда безработицы при начислении зарплаты', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (13, 'НЗ_ЗК_УдержаниеВФондСоцСтрохования', 'Используется для вычисления суммы фонда социального страхования при начислении зарплаты', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (14, 'НЗ_ЗК_НачислениеВПенсионныйФонд', 'Используется для вычисления суммы начисления в пенсионный фонд', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (15, 'НЗ_ЗК_НачислениеВСоцСтрахФонд', 'Используется для вычисления суммы начисления в фонд социального страхования', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (16, 'НЗ_ЗК_НачислениеВФондБезработицы', 'Используется для вычисления суммы начисления в фонд по безработице', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (17, 'НЗ_ЗК_НачислениеВФондНесчСлуч', 'Используется для вычисления суммы начисления в фонд социального страхования по несчастному случаю', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (18, 'НЗ_ЗК_СуммаНачисленнойЗарплаты', 'Используется для вычисления суммы начисленной заработной платы', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (19, 'НЗ_БУ_КоммунальныйНалог', 'НЗ_БУ_КоммунальныйНалог', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (20, 'НЗ_ЗК_НеоблагаемыйМинимум', 'НЗ_ЗК_НеоблагаемыйМинимум', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (22, 'НЗ_БУ_ПрожиточныйМинимум', 'НЗ_БУ_ПрожиточныйМинимум', 0, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (23, 'НЗ_БУ_БазаНалогообложения', 'Возвращает общую сумму базы налогообложения', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (24, 'НЗ_БУ_БазаПодоходныйПенсионный', 'Возвращает базу налогообложения для расчета удержаний в Пенсионный фонд и подоходного налога', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (25, 'НЗ_БУ_ПенсионныйФонд', 'Возвращает сумму удержаний в ПФ с сотрудника', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (26, 'НЗ_БУ_Соцстрах', 'Возвращает сумму удержания с зарплаты в фонд социального страхования', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (27, 'НЗ_БУ_ФондЗанятости', 'Возвращает сумму удержания с зарплаты в фонд занятости (синоним - безработица)', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (28, 'НЗ_БУ_Профвзносы', 'НЗ_БУ_Профвзносы', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (29, 'НЗ_БУ_СтавкаПрофвзносов', 'Возвращает ставку профвзносов в процентах', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (30, 'НЗ_БУ_СПредпрПФ', 'Возвращает ставку начислений на зарплату в Пенсионный фонд для служащих (не льготников), %', 0, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (31, 'НЗ_БУ_СПредпрПФ_льгота', 'Возвращает ставку начислений на зарплату в Пенсионный фонд для служащих-инвалидов, %', 0, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (32, 'НЗ_БУ_СПредпрСоцстрах', 'Возвращает ставку начислений на зарплату в Фонд социального страхования для служащих (не льготников), %', 0, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (33, 'НЗ_БУ_СПредпрСоцстрах_льгота', 'Возвращает ставку начислений на зарплату в Фонд социального страхования для служащих-инвалидов, %', 0, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (34, 'НЗ_БУ_СПредпрФондЗанятости', 'Возвращает ставку начислений на зарплату в Фонд занятости, %', 0, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (35, 'НЗ_БУ_СПредпрНесчСлучай', 'Возвращает ставку начислений на зарплату по страхованию от несчастного случая, %', 0, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (36, 'НЗ_БУ_СуммаПФсПредприятия', 'Возвращает сумму начисления на зарплату в Пенсионный фонд. Параметр 1 - База налогообложения. Параметр 2 - Максимально облагаемая сумма', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (37, 'НЗ_БУ_СуммаСоцстрахсПредприятия', 'Возвращает сумму начисления на зарплату в Фонд социального страхования. Параметр 1 - База налогообложения. Параметр 2 - Максимально облагаемая сумма', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (38, 'НЗ_БУ_СуммаФЗсПредприятия', 'Возвращает сумму начисления на зарплату в Фонд занятости. Параметр 1 - База налогообложения. Параметр 2 - Максимально облагаемая сумма', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (39, 'НЗ_БУ_СуммаНесчСлучайсПредприятия', 'Возвращает сумму начисления на зарплату в Фонд страхования от несчастных случаев. Параметр 1 - База налогообложения. Параметр 2 - Максимально облагаемая сумма', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (40, 'БУ_БланкСтрогойОтчетности', 'Возвращает 1, если ТМЦ является бланком строгой отчетности, и 0, если не является', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (41, 'БУ_Доверенность', 'Возвращает 1, если ТМЦ является доверенностью, и 0, если не является', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (42, 'БУ_Золото', 'Возвращает 1, если ТМЦ является золотом, платиной или драгоценными камнями (для оплаты 5% в ПФ), в противно случае возвращает 0', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (43, 'БУ_СчетПФ_НачислениеЗП', 'Возвращает код субсчета для начисления сбора в ПФ (32% или 4%) в зависимости от статуса служащего (инвалид или нет)', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (44, 'БУ_СчетСоцстраха_НачислениеЗП', 'БУ_СчетСоцстраха_НачислениеЗП', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (45, 'НЗ_ЗК_ПроцентИнвалидов', 'Возвращает % инвалидов к общему числу сотрудников предприятия.', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (46, 'НЗ_ЗК_СтавкаПФИнвалиды', 'Возвращает ставку отчислений в пенсионный фонд для инвалидов в %. Внутренняя функция, не предназначена для использования в проводках.', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (47, 'НЗ_ЗК_СтавкаПФПрочие', 'Возвращает ставку отчислений в пенсионный фонд для служащих, не являющихся инвалидами, в %. Внутренняя функция, не предназначена для использования в проводках.', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (48, 'НЗ_ЗК_СтавкаПФ', 'Возвращает ставку для начисления в Пенсионный фонд В ДОЛЯХ ОТ ЕДИНИЦЫ. Автоматически анализирует % инвалидов на предприятии и статус текущего служащего.', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (49, 'НЗ_ЗК_СтавкаСоцстрахИнвалиды', 'Возвращает ставку отчислений в Фонд социального страхования для инвалидов в %. Внутренняя функция, не предназначена для использования в проводках.', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (50, 'НЗ_ЗК_СтавкаСоцстрахПрочие', 'Возвращает ставку отчислений в Фонд социального страхования для служащих, не являющихся инвалидами, в %. Внутренняя функция, не предназначена для использования в проводках.', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (51, 'НЗ_ЗК_СтавкаСоцстрах', 'Возвращает ставку для начисления в Фонд социального страхования В ДОЛЯХ ОТ ЕДИНИЦЫ. Автоматически анализирует % инвалидов на предприятии и статус текущего служащего.', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (52, 'НЗ_ЗК_СтавкаБезработицы', 'Возвращает ставку для начисления в фонд безработицы В ДОЛЯХ ОТ ЕДИНИЦЫ. Автоматически анализирует % инвалидов на предприятии и статус текущего служащего.', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (53, 'НЗ_ЗК_СтавкаБезработицыПрочие', 'Возвращает ставку отчислений в фонд безработицы для служащих, не являющихся инвалидами, в %. Внутренняя функция, не предназначена для использования в проводках.', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (54, 'НЗ_ЗК_СтавкаБезработицыИнвалиды', 'Возвращает ставку отчислений в фонд безработицы для инвалидов в %. Внутренняя функция, не предназначена для использования в проводках.', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (55, 'НЗ_ЗК_СтавкаУдержанияСоцстрах', 'Возвращает ставку удержания в фонд социального страхования в ДОЛЯХ ОТ ЕДИНИЦЫ', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (56, 'НЗ_ЗК_СтавкаУдержанияБезработица', 'Возвращает ставку удержания в фонд страхования на случай безработицы в ДОЛЯХ ОТ ЕДИНИЦЫ', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (58, 'НЗ_ЗК_СтавкаУдержанияПФ', 'Возвращает 2-й предел (более 150 грн) ставки удержания в Пенсионный фонд в ДОЛЯХ ОТ ЕДИНИЦЫ', 0, 1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (59, 'НЗ_ЗК_КоммунальныйНалог', 'НЗ_ЗК_КоммунальныйНалог', 0, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (60, 'НЗ_БУ_УдержаниеПодоходногоНалога', 'Возвращает сумму подоходного налога для модуля "Бухгалтерия". Используется при автоматичесокм расчете сумм налогов в документе "Начисление зарплаты"', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (61, 'КЗ_СписокАлименты', 'КЗ_СписокАлименты', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (62, 'КЗ_СписокБольничныеОтПредприятия', 'КЗ_СписокБольничныеОтПредприятия', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (63, 'КЗ_СписокБольничныеОтСоцстраха', 'КЗ_СписокБольничныеОтСоцстраха', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (64, 'КЗ_СписокКомпенсационныеВыплаты', 'КЗ_СписокКомпенсационныеВыплаты', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (65, 'КЗ_СписокМатериальнаяПомощь', 'КЗ_СписокМатериальнаяПомощь', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (66, 'КЗ_СписокНедостачи', 'КЗ_СписокНедостачи', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (67, 'КЗ_СписокНесчастныйСлучай', 'КЗ_СписокНесчастныйСлучай', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (68, 'КЗ_СписокОсновнаяЗП', 'КЗ_СписокОсновнаяЗП', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (69, 'КЗ_СписокОтпускные', 'КЗ_СписокОтпускные', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (72, 'КЗ_СписокПремииПоощрения', 'КЗ_СписокПремииПоощрения', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (73, 'КЗ_СписокПрофвзносы', 'КЗ_СписокПпрофвзносы', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (74, 'КЗ_СписокСсуды', 'КЗ_СписокСсуды', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (75, 'НЗ_ЗК_СуммаЛьготыПН', 'НЗ_ЗК_СуммаЛьготыПН', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (76, 'НЗ_ЗК_СтавкаПодоходногоНалога', 'НЗ_ЗК_СтавкаПодоходногоНалога', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (78, 'НЗ_ЗК_РазницаЗП', 'НЗ_ЗК_РазницаЗП', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (79, 'НЗ_ЗК_ПроцентЛьготыПН', 'НЗ_ЗК_ПроцентЛьготыПН', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (80, 'НЗ_ЗК_ПроцентИндексации', 'НЗ_ЗК_ПроцентИндексации', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (81, 'НЗ_ЗК_ПринятВЭтомМесяце', 'НЗ_ЗК_ПринятВЭтомМесяце', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (82, 'НЗ_ЗК_ПризнакЛьготыПН', 'НЗ_ЗК_ПризнакЛьготыПН', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (83, 'НЗ_ЗК_МинимальнаяЗП', 'НЗ_ЗК_МинимальнаяЗП', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (84, 'НЗ_ЗК_ИндексацияЗП', 'НЗ_ЗК_ИндексацияЗП', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (85, 'НЗ_ЗК_ДатаТекущегоКС', 'НЗ_ЗК_ДатаТекущегоКС', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (86, 'КЗ_ТипДоговора', 'КЗ_ТипДоговора', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (87, 'НЗ_БУ_ПризнакЛьготыПН', 'НЗ_БУ_ПризнакЛьготыПН', 1, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (88, 'НЗ_ЗК_УволенВЭтомМесяце', 'НЗ_ЗК_УволенВЭтомМесяце', 0, 1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (89, 'НЗ_ЗК_СтавкаКомНалога', 'НЗ_ЗК_СтавкаКомНалога', 0, 1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (90, 'НЗ_ЗК_ГраничныйДоходЛьготыПН', 'Граничный доход, к которму применяется налоговая социальная льгота', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (91, 'ЗК_ЕСВ_Удержание', 'Сумма удержаний ЕСВ', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (92, 'ЗК_ЕСВ_Начисление', 'Сумма начислений ЕСВ', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (93, 'ЗК_ЕСВ_СтавкаНачислений_ФОП_Прочие', 'Ставка начислений на выплаты входящие в фонд оплаты труда. Величина в процентах.', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (94, 'ЗК_ЕСВ_СтавкаНачислений_ФОП_Инвалиды', 'Ставка начислений на выплаты входящие в фонд оплаты труда для не инвалидов. Величина в процентах.', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (95, 'ЗК_ЕСВ_СтавкаНачислений_ФОП', 'Ставка начислений на выплаты входящие в фонд оплаты труда. Величина в процентах.', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (96, 'ЗК_ЕСВ_СтавкаНачислений_ДВР', 'Ставка начислений на выплаты по договорам за выполненные работы, предоставленные услуги. Величина в процентах.', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (97, 'ЗК_ЕСВ_СтавкаНачислений_ВН_Инвалиды', 'Ставка начислений на выплаты по временной нетрудоспособности для инвалидов. Величина в процентах.', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (98, 'ЗК_ЕСВ_СтавкаНачислений_ВН_Прочие', 'Ставка начислений на выплаты по временной нетрудоспособности для не инвалидов. Величина в процентах.', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (99, 'ЗК_ЕСВ_СтавкаНачислений_ВН', 'Ставка начислений на выплаты по временной нетрудоспособности. Величина в процентах.', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (100, 'ЗК_ЕСВ_СтавкаУдержаний_ФОП', 'Ставка удержаний с выплат входящих в фонд оплаты труда. Величина в процентах.', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (101, 'ЗК_ЕСВ_СтавкаУдержаний_ДВР', 'Ставка удержаний с вознаграждений по договорам за выполненные работы, предоставленные услуги. Величина в процентах.', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (102, 'ЗК_ЕСВ_СтавкаУдержаний_ВН', 'Ставка удержаний с выплат по временной нетрудоспособности. Величина в процентах.', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (103, 'КЗ_ЕСВ_СписокФОП', 'Список выплат основной заработной платы', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (104, 'КЗ_ЕСВ_СписокВН', 'Список выплат по больничным', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (105, 'КЗ_ЕСВ_СписокДВР', 'Список выплат по договорам', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (106, 'КЗ_ЕСВ_СубсчетНачислений', 'КЗ_ЕСВ_СубсчетНачислений', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (107, 'КЗ_ЕСВ_СубсчетУдержаний', 'КЗ_ЕСВ_СубсчетУдержаний', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (108, 'БУ_ЕСВ_Начисление_ФОП', 'БУ_ЕСВ_Начисление_ФОП', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (109, 'БУ_ЕСВ_Удержание_ФОП', 'БУ_ЕСВ_Удержание_ФОП', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (110, 'БУ_ЕСВ_Начисление_ВН', 'БУ_ЕСВ_Начисление_ВН', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (111, 'БУ_ЕСВ_Удержание_ВН', 'БУ_ЕСВ_Удержание_ВН', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (112, 'БУ_ЕСВ_Начисление_ДВР', 'БУ_ЕСВ_Начисление_ДВР', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (113, 'БУ_ЕСВ_Удержание_ДВР', 'БУ_ЕСВ_Удержание_ДВР', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (114, 'БУ_ЕСВ_Начисление', 'БУ_ЕСВ_Начисление', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (115, 'БУ_ЕСВ_Удержание', 'БУ_ЕСВ_Удержание', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (116, 'НЗ_ЗК_СтавкаПодоходногоНалога2', 'НЗ_ЗК_СтавкаПодоходногоНалога2', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (117, 'НЗ_ЗК_БазисПодоходногоНалога', 'НЗ_ЗК_БазисПодоходногоНалога', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (118, 'НЗ_БУ_СуммаСтавкиПодоходногoНалога2', 'НЗ_БУ_СуммаСтавкиПодоходногoНалога2', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (119, 'КЗ_СуммаПредыдущихПозиций', 'КЗ_СуммаПредыдущихПозиций', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (120, 'ЗК_ЕСВ_УдержаниеПоТипуВыплаты', 'ЗК_ЕСВ_УдержаниеПоТипуВыплаты', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (121, 'ЗК_ЕСВ_НачислениеПоТипуВыплаты', 'ЗК_ЕСВ_НачислениеПоТипуВыплаты', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (122, 'БУ_Валюта_СтавкаКомиссииБанка', 'Процент комиссии банка за услуги при покупке валюты (%)', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (123, 'НЗ_ЗК_ГраничнаяСуммаПочтовогоСбора', 'НЗ_ЗК_ГраничнаяСуммаПочтовогоСбора', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (124, 'НЗ_ЗК_РазмерПочтовогоСбора', 'НЗ_ЗК_РазмерПочтовогоСбора', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (125, 'НЗ_ЗК_РазмерПочтовогоСбора2', 'НЗ_ЗК_РазмерПочтовогоСбора2', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (126, 'НЗ_ЗК_ПроцентПочтовогоСбора', 'НЗ_ЗК_ПроцентПочтовогоСбора', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (127, 'НЗ_ЗК_ДетейПоЛьготе', 'НЗ_ЗК_ДетейПоЛьготе', 0, -1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (128, 'ЗК_ВоенныйСбор_СтавкаУдержаний', 'ЗК_ВоенныйСбор_СтавкаУдержаний', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (129, 'НЗ_ЗК_УдержаниеВоенногоСбора', 'НЗ_ЗК_УдержаниеВоенногоСбора', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (130, 'ЗК_ЕСВ_КоэффициентНачислений', 'ЗК_ЕСВ_КоэффициентНачислений', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (131, 'КЗ_КорректировкаЕСВ', 'Формирование расчетной ведомости используя данные из двух режимов: "Начисление заработной платы за месяц" и "Начисление заработной платы за месяц: Корректировка ЕСВ".', 1, 1);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (132, 'НЗ_ЗК_ПроцентИндексацииПредКС', 'НЗ_ЗК_ПроцентИндексацииПредКС', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (133, 'НЗ_ЗК_ИндексацияЗПФИКС', 'НЗ_ЗК_ИндексацияЗПФИКС', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (134, 'НЗ_БУ_ПроцентЛьготыПН', 'НЗ_БУ_ПроцентЛьготыПН', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (135, 'НЗ_ЗК_ИндексацияПредКС', 'НЗ_ЗК_ИндексацияПредКС', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (136, 'ЗК_ЕСВ_КоэффициентНачисленийКор', 'ЗК_ЕСВ_КоэффициентНачисленийКор', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (137, 'НЗ_ЗК_НачислениеДоУровняМинЗП', 'НЗ_ЗК_НачислениеДоУровняМинЗП', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (138, 'НЗ_ЗК_КоэффициентСрЗП', 'НЗ_ЗК_КоэффициентСрЗП', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (139, 'НЗ_ЗК_СуммаНалоговойСоциальнойЛьготы', 'НЗ_ЗК_СуммаНалоговойСоциальнойЛьготы', 1, 0);
INSERT dbo.z_FRUDFR(UDFID, UDFName, UDFDesc, IsInt, RevID) VALUES (140, 'НЗ_ЗК_НачислениеДоСреднОкладаКоман', 'НЗ_ЗК_НачислениеДоСреднОкладаКоман', 1, 0);
