INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (-10, 'Настройки пользователя', 14, 0);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (0, 'Прочее', 20, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (1, 'Общие параметры', 1, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (2, 'Параметры НДС', 2, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (3, 'Открытый период', 3, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (4, 'Склад', 4, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (5, 'Склад 2', 5, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (6, 'Цены', 6, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (7, 'Бухгалтерия', 7, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (9, 'Кадры и Зарплата', 9, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (10, 'Метод списания', 10, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (11, 'Монитор наценки', 11, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (12, 'Сканер штрихкодов', 12, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (13, 'Анализатор', 13, 0);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (14, 'Дисконтная система', 15, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (15, 'Торговые модули', 16, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (200, 'Системные значения', 18, 0);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (11000, 'Бизнес', 8, 1);
INSERT dbo.z_VarPages(VarPageCode, VarPageName, VarPagePosID, VarPageVisible) VALUES (37000, 'Синхронизация', 17, 0);
