INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1, 10106, 'Выбор из справочника предприятий', 10250, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (2, 10107, 'Поиск в справочнике предприятий', 10250, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (3, 11611, 'Монитор товара', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (4, 11614, 'Монитор заказа внешнего', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (6, 11614, 'Монитор заказа внутреннего', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (8, 10601, 'Монитор документа', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (9, 10601, 'Монитор документа: Продажа товара оператором', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (10, 11612, 'Монитор сертификатов', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (12, 11108, 'Подбор по каталогу', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (14, 11107, 'Поиск товара', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (15, 11621, 'Монитор возврата товара поставщику', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (16, 11621, 'Монитор возврата товара от получателя', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (17, 11615, 'Монитор наценки', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (18, 11616, 'Монитор переоценки', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (19, 14621, 'Монитор возврата ТМЦ от получателя', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (20, 14621, 'Монитор возврата ТМЦ поставщику', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (21, 14611, 'Монитор ТМЦ', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (22, 10801, 'Истекшие резервы по счетам', 11001, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (23, 10801, 'Уведомления внешних заказов', 11211, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (24, 10801, 'Уведомления внутренних заказов', 11221, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (25, 10106, 'Выбор из справочника внутренних фирм', 10110, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (26, 10106, 'Выбор из справочника складов', 10310, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (27, 10107, 'Поиск в справочнике внутренних фирм', 10110, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (28, 10107, 'Поиск в справочнике складов', 10310, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (29, 10602, 'Выбор связанного документа', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (30, 14601, 'Признаки и проводки', 0, NULL, NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (32, 10952, 'Расчет остатков на дату', 0, 'EXEC t_CalcRemByDate NULL, #Параметр_Расчитать остатки на дату:Дата#', 'Запустить инструмент ''Расчет остатков на дату''?', 'Выполнение инструмента ''Расчет остатков на дату'' завершено.', 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (33, 10952, 'Расчет текущих остатков', 0, 'EXEC t_CalcRem', 'Запустить инструмент ''Расчет текущих остатков''?', 'Выполнение инструмента ''Расчет текущих остатков'' завершено.', 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (34, 10952, 'Фиксированный  шаблон', 0, 'EXEC  z_DocShedFixed #Параметр_Код документа#, #Параметр_Код регистрации#, #Параметр_Код шаблона#', NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (35, 10952, 'Ежемесячная оплата равными частями', 0, 'EXEC z_DocShedMonthly #Параметр_Код документа#, #Параметр_Код регистрации#, #Параметр_Сумма:Строка#, #Параметр_Срок оплаты (месяцев):Строка#, #Параметр_День платежа (1-31):Строка#, #Параметр_Дата начала:Дата#, #Параметр_Код валюты#', NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (36, 10952, 'Еженедельная оплата равными частями', 0, 'EXEC  z_DocShedWeekly  #Параметр_Код документа#, #Параметр_Код регистрации#, #Параметр_Сумма:Строка#, #Параметр_Срок оплаты (недель):Строка#, #Параметр_День платежа (1-7):Строка#, #Параметр_Дата начала:Дата#, #Параметр_Код валюты#', NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (37, 10952, 'Ежедневная оплата равными частями', 0, 'EXEC  z_DocShedDaily  #Параметр_Код документа#, #Параметр_Код регистрации#, #Параметр_Сумма:Строка#, #Параметр_Срок оплаты (дней):Строка#, #Параметр_Дата начала:Дата#, #Параметр_Код валюты#', NULL, NULL, 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (38, 10952, 'Удаление нулевых остатков', 0, 'IF dbo.zf_Var(''t_ZeroRems'') = 1 
  RAISERROR (''Удаление нулевых остатков запрещено общими настройками системы'', 16, 1) 
ELSE 
  DELETE FROM t_Rem WHERE Qty = 0 AND AccQty = 0', 'Запустить инструмент ''Удаление нулевых остатков''?', 'Выполнение инструмента ''Удаление нулевых остатков'' завершено.', 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (39, 10952, 'Удаление нулевых остатков на дату', 0, 'IF dbo.zf_Var(''t_ZeroDateRems'') = 1 
  RAISERROR (''Удаление нулевых остатков на дату запрещено общими настройками системы'', 16, 1) 
ELSE 
  DELETE FROM t_RemD WHERE Qty = 0 AND AccQty = 0', 'Запустить инструмент ''Удаление нулевых остатков на дату''?', 'Выполнение инструмента ''Удаление нулевых остатков на дату'' завершено.', 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (40, 10952, 'Расчет остатков ТМЦ на дату', 0, 'EXEC b_CalcRemByDate NULL, #Параметр_Рассчитать остатки на дату:Дата#', 'Запустить инструмент ''Расчет остатков ТМЦ на дату''?', 'Выполнение инструмента ''Расчет остатков ТМЦ на дату'' завершено.', 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (41, 10952, 'Расчет текущих остатков ТМЦ', 0, 'EXEC b_CalcRem', 'Запустить инструмент ''Расчет текущих остатков ТМЦ''?', 'Выполнение инструмента ''Расчет текущих остатков ТМЦ'' завершено.', 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (42, 11106, 'Проводник по товарам', 0, '', '', '', 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (43, 10952, 'Начисление бонусов на дисконтную карту', 0, 'SET NOCOUNT ON 
IF NOT EXISTS(SELECT TOP 1 1 FROM z_DocDC WHERE DocCode = #Параметр_Код документа#
AND ChID = #Параметр_Код регистрации# AND DCardChID = #Параметр_Код регистрации#)
INSERT INTO z_DocDC(DocCode, ChID, DCardChID)
VALUES(#Параметр_Код документа#, #Параметр_Код регистрации#, #Параметр_Код регистрации#)
DECLARE @NEXT_ID int  SELECT @NEXT_ID=ISNULL(MAX(LogID), 0)+1 FROM z_LogDiscRec WITH (XLOCK, HOLDLOCK)
INSERT INTO z_LogDiscRec(LogID, DCardChID, TempBonus, DocCode, ChID, SrcPosID, DiscCode, SumBonus, LogDate, DBiID)
VALUES (@NEXT_ID, #Параметр_Код регистрации#, 0, #Параметр_Код документа#, #Параметр_Код регистрации#, NULL, 0, #Параметр_Сумма:Дробное#, GETDATE(), dbo.zf_var(''OT_DBiID''))
SET NOCOUNT OFF', '', '', 1, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1044, 10952, 'Сформировать имена и примечания столиков', 10601, 'UPDATE r_Desks SET DeskName = g.DeskGName + '' - '' + 
CAST((SELECT COUNT(d2.DeskCode) FROM r_Desks d2 
WHERE d2.DeskCode <> 0 AND d2.DeskCode < d1.DeskCode AND d1.DeskGCode = d2.DeskGCode) + 1 AS varchar(10)),     
Notes = #Параметр_Префикс примечания:Строка# + CAST((SELECT COUNT(d2.DeskCode) 
FROM r_Desks d2 WHERE d2.DeskCode <> 0 AND d2.DeskCode < d1.DeskCode 
AND d1.DeskGCode = d2.DeskGCode) + 1 AS varchar(10)) FROM r_Desks d1, r_DeskG g WHERE d1.DeskCode <> 0 AND d1.DeskGCode = g.DeskGCode AND 
d1.DeskGCode = CASE #Параметр_Группа столиков:Целое# WHEN '''' THEN 0 ELSE #Параметр_Группа столиков:Целое# END', '', '', 1, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1045, 10106, 'Выбор из справочника дисконтных карт', 10400, '', '', '', 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1046, 10107, 'Поиск в справочнике дисконтных карт', 10400, '', '', '', 0, NULL);
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1047, 11011, 'Отложить чек', 0, 'act_Suspend', '', '', 0, 'Ctrl + S');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1048, 11011, 'Перейти к чеку', 0, 'act_GoToCheque', '', '', 0, 'Ctrl + G');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1049, 11011, 'Поиск цены', 0, 'act_Find', '', '', 0, 'Ctrl + F');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1050, 11011, 'Подбор товара по каталогу', 0, 'act_ProdSelect', '', '', 0, 'Ctrl + E');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1051, 11011, 'Возвратный чек', 0, 'act_Ret', '', '', 0, 'Ctrl + Alt + F6');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1052, 11011, 'Выбор возврата', 0, 'act_RetSelect', '', '', 0, 'Ctrl + R');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1053, 11011, 'Идентификация служащего', 0, 'act_ShowEmpID', '', '', 0, 'F9');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1054, 11011, 'Параметры чека', 0, 'act_ChequeParams', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1055, 11011, 'Заблокировать', 0, 'act_Lock', '', '', 0, 'Ctrl + L');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1056, 11012, 'Открыть денежный ящик', 0, 'act_OpenMoneyBox', '', '', 0, 'Ctrl + Alt + M');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1057, 11012, 'Копия чека', 0, 'act_ChequeCopy', '', '', 0, 'Ctrl + Alt + C');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1058, 11012, 'Нулевой чек', 0, 'act_ZeroCheque', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1059, 11012, 'Служебный внос', 0, 'act_MonRec', '', '', 0, 'Ctrl + Alt + I');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1060, 11012, 'Служебный вынос', 0, 'act_MonExp', '', '', 0, 'Ctrl + Alt + O');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1061, 11013, 'Касса', 0, 'act_Cash', '', '', 0, 'F7');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1062, 11013, 'X-отчет', 0, 'act_XRep', '', '', 0, 'Ctrl + Alt + X');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1063, 11013, 'Сокращенный отчет за период', 0, 'act_ShortDateRep', '', '', 0, 'Ctrl + Alt + S');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1064, 11013, 'Сокращенный отчет по номерам', 0, 'act_ShortNumReport', '', '', 0, 'Ctrl + Alt + T');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1065, 11013, 'Отчет за период', 0, 'act_DateRep', '', '', 0, 'Ctrl + Alt + D');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1066, 11013, 'Отчет по номерам', 0, 'act_NumRep', '', '', 0, 'Ctrl + Alt + N');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1067, 11013, 'Z-отчет', 0, 'act_ZRep', '', '', 0, 'Ctrl + Alt + Z');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1068, 10801, 'Расформирование временных должностей', 15092, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1069, 11014, 'Новый чек', 0, 'act_New', NULL, NULL, 0, 'F6');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1070, 11014, 'Редактировать', 0, 'act_Edit', NULL, NULL, 0, 'F4');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1071, 11014, 'Режим отмены продаж', 0, 'act_CancelMode', NULL, NULL, 0, 'Ctrl + F8');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1072, 11014, 'Закрыть чек', 0, 'act_Close', NULL, NULL, 0, 'F10');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1073, 11014, 'Дополнительно', 0, 'act_More', NULL, NULL, 0, 'F5');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1074, 11014, 'Отмена всего чека', 0, 'act_Anul', NULL, NULL, 0, 'Ctrl + F12');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1075, 10952, 'Удаление партий без движения', 0, 'EXECUTE t_DeleteDeadPPs', 'Партии, движение по которым отсутствует, будут удалены. Продолжить?', 'Операция завершена', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1076, 10953, 'Калькуляционная карта: Копирование документа', 0, 'Торговля\Документы\Инструмент - Калькуляционная карта - Копирование.fr3', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1077, 10953, 'Калькуляционная карта: Обновление Справочника товаров: Комплектация', 0, 'Торговля\Документы\Инструмент - Калькуляционная карта - Справочник товаров - Комплектация.fr3', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1078, 10953, 'Калькуляционная карта: Редактор технологии', 0, 'Торговля\Документы\Инструмент - Калькуляционная карта - Редактирование технологии.fr3', '', '', 1, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1079, 10953, 'Комплектация товара: Формирование на основе продаж', 0, 'Торговля\Документы\Инструмент - Комплектация товара - Формирование на основе продаж.fr3', '', '', 1, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1080, 10952, 'Комплектация товара: Расчет составляющих', 0, 'EXECUTE t_SRecSpecCalc #Параметр_Код регистрации#', '', '', 1, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1081, 10106, 'Выбор из справочника признаков 1', 10151, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1082, 10106, 'Выбор из справочника признаков 2', 10152, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1083, 10106, 'Выбор из справочника признаков 3', 10153, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1084, 10106, 'Выбор из справочника признаков 4', 10154, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1085, 10106, 'Выбор из справочника признаков 5', 10155, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1086, 10106, 'Выбор из справочника прайс-листов', 10170, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1087, 10106, 'Выбор из справочника складов: группы', 10300, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1088, 10106, 'Выбор из справочника предприятий: группы', 10200, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1089, 10106, 'Выбор из справочника товаров: категории', 10331, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1090, 10106, 'Выбор из справочника товаров: группы', 10332, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1091, 10106, 'Выбор из справочника товаров: 1 группа', 10333, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1092, 10106, 'Выбор из справочника товаров', 10350, '', '', '', 0, '');
INSERT dbo.z_Tools(ToolCode, RepToolCode, ToolName, DocCode, ExecStr, ConfirmText, CompleteText, RefreshOnComplete, ShortCut) VALUES (1093, 10953, 'Экспорт электронной отчетности', 0, 'Общие\Документы\Экспорт электронной отчетности.fr3', '', '', 0, '');
