INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 1, 1, 11040001, 't_Cos_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 2, 3, 11003001, 't_Ret_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 3, 5, 11003001, 't_Ret_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 4, 7, 11003001, 't_Ret_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 5, 9, 11004001, 't_CRRet_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 6, 11, 11004001, 't_CRRet_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 7, 13, 11004001, 't_CRRet_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 8, 15, 11011001, 't_CRet_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 9, 17, 11212001, 't_EORec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 10, 19, 11212001, 't_EORec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 11, 21, 11211001, 't_EOExp_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 12, 23, 11211001, 't_EOExp_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 13, 25, 11221001, 't_IORec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 14, 27, 11221001, 't_IORec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 16, 31, 11221001, 't_IORec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 17, 33, 11221001, 't_IORec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 18, 35, 11021001, 't_Exc_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 19, 37, 11021001, 't_Exc_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 20, 39, 11021001, 't_Exc_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 21, 41, 11311001, 't_SPRec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 22, 43, 11312001, 't_SPExp_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 23, 45, 11002001, 't_Rec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 24, 47, 11002001, 't_Rec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 25, 49, 11002001, 't_Rec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 26, 51, 11002001, 't_Rec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 27, 53, 11002001, 't_Rec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 28, 55, 11002001, 't_Rec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 29, 57, 11002001, 't_Rec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 30, 59, 11045001, 't_Cst_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 31, 61, 11045001, 't_Cst_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 32, 63, 11045001, 't_Cst_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 33, 65, 11045001, 't_Cst_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 34, 67, 11045001, 't_Cst_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 35, 69, 11045001, 't_Cst_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 36, 71, 11045001, 't_Cst_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 37, 73, 11045001, 't_Cst_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 38, 75, 11035001, 't_Sale_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 40, 79, 11231001, 't_Dis_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 41, 81, 11231001, 't_Dis_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 42, 83, 11012001, 't_Inv_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 43, 85, 11015001, 't_Exp_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 44, 87, 11001001, 't_Acc_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 45, 89, 11001001, 't_Acc_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 46, 91, 11001001, 't_Acc_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 47, 93, 11001001, 't_Acc_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 48, 95, 11001001, 't_Acc_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (1, 49, 97, 11221001, 't_IORec_1', 0, 0, 'NONE');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 1, 2, 11040002, 't_CosD_2', 1, 0, 't_Cos.ChID = t_CosD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 2, 4, 11003002, 't_RetD_2', 1, 0, 't_Ret.ChID = t_RetD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 3, 6, 11003002, 't_RetD_2', 1, 0, 't_Ret.ChID = t_RetD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 4, 8, 11003002, 't_RetD_2', 1, 0, 't_Ret.ChID = t_RetD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 5, 10, 11004002, 't_CRRetD_2', 1, 0, 't_CRRet.ChID = t_CRRetD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 6, 12, 11004002, 't_CRRetD_2', 1, 0, 't_CRRet.ChID = t_CRRetD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 7, 14, 11004002, 't_CRRetD_2', 1, 0, 't_CRRet.ChID = t_CRRetD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 8, 16, 11011002, 't_CRetD_2', 1, 0, 't_CRet.ChID = t_CRetD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 9, 18, 11212002, 't_EORecD_2', 1, 0, 't_EORec.ChID = t_EORecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 10, 20, 11212002, 't_EORecD_2', 1, 0, 't_EORec.ChID = t_EORecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 11, 22, 11211002, 't_EOExpD_2', 1, 0, 't_EOExp.ChID = t_EOExpD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 12, 24, 11211002, 't_EOExpD_2', 1, 0, 't_EOExp.ChID = t_EOExpD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 13, 26, 11221002, 't_IORecD_2', 1, 0, 't_IORec.ChID = t_IORecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 14, 28, 11221002, 't_IORecD_2', 1, 0, 't_IORec.ChID = t_IORecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 16, 32, 11221002, 't_IORecD_2', 1, 0, 't_IORec.ChID = t_IORecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 17, 34, 11221002, 't_IORecD_2', 1, 0, 't_IORec.ChID = t_IORecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 18, 36, 11021002, 't_ExcD_2', 1, 0, 't_Exc.ChID = t_ExcD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 19, 38, 11021002, 't_ExcD_2', 1, 0, 't_Exc.ChID = t_ExcD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 20, 40, 11021002, 't_ExcD_2', 1, 0, 't_Exc.ChID = t_ExcD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 21, 42, 11311003, 't_SPRecA_2', 1, 0, 't_SPRec.ChID = t_SPRecA.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 22, 44, 11312003, 't_SPExpA_2', 1, 0, 't_SPExp.ChID = t_SPExpA.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 23, 46, 11002002, 't_RecD_2', 1, 0, 't_Rec.ChID = t_RecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 24, 48, 11002002, 't_RecD_2', 1, 0, 't_Rec.ChID = t_RecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 25, 50, 11002002, 't_RecD_2', 1, 0, 't_Rec.ChID = t_RecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 26, 52, 11002002, 't_RecD_2', 1, 0, 't_Rec.ChID = t_RecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 27, 54, 11002002, 't_RecD_2', 1, 0, 't_Rec.ChID = t_RecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 28, 56, 11002002, 't_RecD_2', 1, 0, 't_Rec.ChID = t_RecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 29, 58, 11002002, 't_RecD_2', 1, 0, 't_Rec.ChID = t_RecD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 30, 60, 11045002, 't_CstD_2', 1, 0, 't_Cst.ChID = t_CstD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 31, 62, 11045002, 't_CstD_2', 1, 0, 't_Cst.ChID = t_CstD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 32, 64, 11045002, 't_CstD_2', 1, 0, 't_Cst.ChID = t_CstD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 33, 66, 11045002, 't_CstD_2', 1, 0, 't_Cst.ChID = t_CstD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 34, 68, 11045002, 't_CstD_2', 1, 0, 't_Cst.ChID = t_CstD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 35, 70, 11045002, 't_CstD_2', 1, 0, 't_Cst.ChID = t_CstD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 36, 72, 11045002, 't_CstD_2', 1, 0, 't_Cst.ChID = t_CstD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 37, 74, 11045002, 't_CstD_2', 1, 0, 't_Cst.ChID = t_CstD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 38, 76, 11035002, 't_SaleD_2', 1, 0, 't_Sale.ChID = t_SaleD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 40, 80, 11231002, 't_DisD_2', 1, 0, 't_Dis.ChID = t_DisD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 41, 82, 11231002, 't_DisD_2', 1, 0, 't_Dis.ChID = t_DisD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 42, 84, 11012002, 't_InvD_2', 1, 0, 't_Inv.ChID = t_InvD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 43, 86, 11015002, 't_ExpD_2', 1, 0, 't_Exp.ChID = t_ExpD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 44, 88, 11001002, 't_AccD_2', 1, 0, 't_Acc.ChID = t_AccD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 45, 90, 11001002, 't_AccD_2', 1, 0, 't_Acc.ChID = t_AccD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 46, 92, 11001002, 't_AccD_2', 1, 0, 't_Acc.ChID = t_AccD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 47, 94, 11001002, 't_AccD_2', 1, 0, 't_Acc.ChID = t_AccD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 48, 96, 11001002, 't_AccD_2', 1, 0, 't_Acc.ChID = t_AccD.ChID');
INSERT dbo.z_WCopyT(TablePosID, CopyID, AChID, TableCode, TableSuffix, ParentPosID, JoinType, RelName) VALUES (2, 49, 98, 11221002, 't_IORecD_2', 1, 0, 't_IORec.ChID = t_IORecD.ChID');
