INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (0, 0, 'Нет проводки', '', 0, 0, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (1, 579, 'Возвращен обьект аренды арендодателю', '', 1, 29, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (10, 575, 'Получен объект необоротных активов в операционную аренду', '', 1, 29, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (72, 341, 'Списана стоимость невозмещенных недостач (по истечению срока исковой давности)', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (101, 588, 'Входящие остатки необоротных аткивов', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (301, 562, 'Входящие остатки в кассе в национальной валюте', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (302, 563, 'Входящие остатки в кассе в иностранной валюте', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (311, 560, 'Входящие остатки на расчетном счете', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (312, 561, 'Входящие остатки на валютном счете', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (601, 617, 'Входящие краткосрочные кредиты банков в национальной валюте', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (661, 576, 'Входящая задолженность по заработной плате', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (662, 622, 'Входящая задолженность по депонированной зарплате', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (1000, 611, 'Начислена амортизация необоротных активов в налоговом учете', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (5001, 616, 'Отражены гарантии на забалансовом счете', '', 1, 18, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28100, 583, 'Входящие остатки ТМЦ (количественный учет)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28101, 584, 'Входящие остатки товаров (суммовой учет, оптовая торговля)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28200, 586, 'Входящие остатки товаров в рознице (суммовой учет в ценах прихода)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28201, 587, 'Входящие остатки товаров в рознице (суммовой учет в ценах реализации)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (36100, 567, 'Входящая дебиторская задолженность (покупатели)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (36101, 568, 'Входящая кредиторская задолженность (покупатели)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (36200, 618, 'Входящая дебиторская задолженность (иностранные покупатели)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (36201, 619, 'Входящая кредиторская задолженность (иностранные покупатели)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (37101, 573, 'Входящие остатки по авансам оплаченным', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (37701, 574, 'Входящая дебиторская задолженность (прочие дебиторы)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (37702, 620, 'Входящая кредиторская задолженность (прочие дебиторы)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (63100, 564, 'Входящая дебиторская задолженность (поставщики)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (63101, 565, 'Входящая кредиторская задолженность (поставщики)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (68101, 572, 'Входящие остатки по авансам полученным', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (68503, 621, 'Входящая кредиторская задолженность по исполнительным листам', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (101151, 82, 'Ввод в эксплуатацию необоротных активов (ОС, НМА, прочие необоротные материальные активы)', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (102201, 285, 'Отнесены ТМЦ на увеличение стоимости необоротных активов', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (103631, 276, 'Модернизация необоротных активов (ОС, НМА, прочие) (услуга от поставщика)', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (151372, 21, 'Списаны подотчетные расходы на приобретение необоротных активов', '', 1, 2, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (152422, 164, 'Поступление взносов необоротными активами', '', 1, 14, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (152460, 107, 'Поступление взносов в уставный фонд необоротными активами', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (152631, 210, 'Приход необоротных активов (ОС, НМА, прочие) от поставщика', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (152651, 461, 'Начислен сбор в Пенсионный фонд при приобретении ОС (автомобиль)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (201372, 26, 'Списаны подотчетные расходы на приобретение ТМЦ', '', 1, 2, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (201422, 166, 'Поступление взносов ТМЦ', '', 1, 14, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (201460, 109, 'Поступление взносов в уставный фонд ТМЦ', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (281281, 334, 'Перемещение ТМЦ между оптовыми складами', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (281631, 6, 'Получены ТМЦ от поставщика на оптовый склад', '', 1, 3, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (281632, 100000005, 'Приход импортного товара', '', 0, 0, 0, 'ПО-380245-281632');
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (301311, 1, 'Получены наличные по чеку', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (301361, 484, 'Поступила оплата в кассу за товар, услуги (оптовая торговля)', '', 1, 4, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (301372, 2, 'Возврат неиспользованных денежных средств', '', 1, 2, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (301375, 343, 'Внесена сумма возмещения ущерба в кассу предприятия', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (301377, 57, 'Возвращена ссуда через кассу предприятия', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (301422, 162, 'Поступление взносов через кассу предприятия', '', 1, 14, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (301460, 105, 'Поступление взносов в уставный фонд через кассу предприятия', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (311301, 3, 'Сданы денежные средства из кассы в банк', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (311333, 417, 'Зачислен остаток денег, перечисленных на покупку валюты', '', 1, 20, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (311361, 37, 'Поступила оплата за товар, услуги (оптовая торговля)', '', 1, 4, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (311422, 163, 'Поступление взносов на расчетный счет', '', 1, 14, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (311460, 106, 'Поступление взносов в уставный фонд на расчетный счет', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (311601, 373, 'Получен краткосрочный кредит в национальной валюте', '', 1, 18, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (311631, 49, 'Получены денежные средства за возвращенный товар от поставщика', '', 1, 3, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (311690, 566, 'Поступила арендная плата авансом за несколько периодов', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (311732, 440, 'Зачислены проценты по остаткам средств на счете', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (312333, 100000003, 'Покупка иностранной валюты (Валютный счет: Приход)', '', 0, 0, 0, 'ПО-380245-312333');
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (312334, 419, 'Зачислен остаток денег, перечисленных на продажу валюты', '', 1, 21, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (312460, 117, 'Получены взносы в иностранной валюте', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (312632, 100000004, 'Перечислены деньги поставщику (импорт)', '', 0, 0, 0, 'ПО-380245-312632');
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (333301, 491, 'Сданы инкассатору наличные деньги', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (333311, 399, 'Перечислены денежные средства на покупку валюты(переименовано обновлением 3.8.0.245)', '', 1, 20, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (334312, 405, 'Перечислены денежные средства на продажу валюты', '', 1, 21, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (361311, 42, 'Перечислены деньги за возвращенный товар (оптовая торговля)', '', 1, 4, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (361702, 36, 'Отгружен товар покупателю (оптовая торговля)', '', 1, 4, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (361703, 59, 'Оказана услуга заказчику', '', 1, 4, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (372301, 4, 'Выданы денежные средства в подотчет', '', 1, 2, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (375716, 477, 'Установлено виновное лицо после списания ТМЦ, основных средств', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (377102, 259, 'Реализованы необоротные активы (ОС, НМА, прочие)', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (377301, 56, 'Выдана ссуда работнику', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (390311, 441, 'Оплачен торговый патент', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (400672, 126, 'Уменьшение номинальной стоимости акций', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (422103, 180, 'Возвращены взносы необоротными активами', '', 1, 14, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (422201, 191, 'Возвращены взносы ТМЦ', '', 1, 14, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (422301, 177, 'Возвращены взносы через кассу предприятия', '', 1, 14, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (422311, 178, 'Возвращены взносы с расчетного счета', '', 1, 14, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (441442, 481, 'Списаны непокрытые убытки за счет нераспределенной прибыли', '', 1, 26, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (441443, 479, 'Уменьшена нераспределенная прибыль на прибыль, использованную в отчетном периоде', '', 1, 26, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (442443, 480, 'Увеличены непокрытые убытки на прибыль, использованную в отчетном периоде', '', 1, 26, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (443671, 265, 'Начислены дивиденды', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (460103, 132, 'Возврат взносов в уставный фонд необоротными активами', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (460201, 151, 'Возврат взносов в уставный фонд ТМЦ', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (460301, 129, 'Возврат взносов в уставный фонд через кассу предприятия', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (460311, 130, 'Возврат взносов в уставный фонд с расчетного счета предприятия', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (460312, 593, 'Возврат взносов иностранному инвестору', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (460400, 104, 'Отражен размер уставного капитала', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (631281, 48, 'Возвращены ТМЦ поставщику', '', 1, 3, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (631301, 623, 'Оплата через кассу за товар, услуги', '', 1, 3, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (641390, 482, 'Списана стоимость патента на расчеты с бюджетом', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (656311, 77, 'Перечислены взносы по страхованию от несчастного случая', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (661301, 51, 'Выдана заработная плата', '', 1, 7, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (661662, 53, 'Депонирована заработная плата', '', 1, 7, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (662301, 55, 'Выдана депонированная заработная плата', '', 1, 7, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (671301, 502, 'Выплачены дивиденды через кассу', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (671311, 504, 'Перечислены дивиденды с расчетного счета', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (672301, 127, 'Выплачена компенсация за уменьшение стоимости акций', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (672311, 128, 'Перечислена компенсация за уменьшение стоимости акций', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (684311, 427, 'Перечислены проценты по векселю', '', 1, 23, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (690713, 570, 'Включена в доход арендная плата, приходящаяся на отчетный период', '', 1, 29, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (704361, 41, 'Возврат товара от покупателя (оптовая торговля)', '', 1, 4, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (811661, 50, 'Начисление заработной платы', '', 1, 7, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (831131, 79, 'Начисление износа необоротных активов (ОС, НМА, прочих необоротных материальных активов)', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (840311, 439, 'Оплачены услуги банка', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (840372, 5, 'Списаны подотчетные расходы на финансовый результат', '', 1, 2, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (902209, 243, 'Списаны со склада бланки строгой отчетности', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (920201, 293, 'Списаны ТМЦ на ремонт необоротных активов (ОС, НМА, прочие)', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (920390, 483, 'Списана на расходы стоимость патентов, не перекрытых прибылью', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (920631, 8, 'Получены услуги от поставщика', '', 1, 3, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (943201, 63, 'Реализованы производственные запасы', '', 1, 4, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (949684, 426, 'Отражены расходы по уплате процентов по векселю', '', 1, 23, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (976101, 464, 'Списана недостача необоротных активов', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (981170, 550, 'Корректировка налога на прибыль (налог в БУ > налога в НУ)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (981641, 551, 'Корректировка налога на прибыль (налог в БУ < налога в НУ)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (3720100, 580, 'Входящая дебиторская задолженность подотчетного лица', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (3720101, 581, 'Входящая кредиторская задолженность подотчетного лица', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (3771301, 72, 'Выданы алименты через кассу предприятия', '', 1, 7, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (6412311, 443, 'Оплачен акцизный сбор', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (6415311, 458, 'Оплачен налог на добавленную стоимость', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (6417311, 447, 'Оплачен единый налог', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (6419311, 455, 'Оплачен комунальный налог', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (6427311, 457, 'Оплачен налог на землю', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (6428311, 445, 'Оплачен рыночный сбор', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (6850100, 569, 'Входящая дебиторская задолженность (прочие кредиторы)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (6850101, 571, 'Входящая кредиторская задолженность (прочие кредиторы)', '', 1, 30, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (7016412, 442, 'Начислен акцизный сбор', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (7016428, 444, 'Начислен рыночный сбор', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (8406417, 446, 'Начислен единый налог', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (8406427, 456, 'Начислен налог на землю', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (9816416, 463, 'Начислен налог на прибыль', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (10171900, 501, 'Приход излишков необоротных активов', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (10171901, 339, 'Приход излишков необоротных активов (без корректировки НДС)', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (20174600, 226, 'Оприходовано сырье или материалы после ликвидации необоротных активов (ОС, НМА, прочие необоротные материальные активы)', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (20174601, 234, 'Оприходовано сырье или материалы после ликвидации необоротных активов при самостоятельном решении', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (22071900, 60, 'Возвращены на склад МБП из эксплуатации', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28128100, 516, 'Перемещение товаров между оптовыми складами (суммовой учет)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28128200, 331, 'Перемещение товара из розницы на оптовый склад (учет в ценах прихода)', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28128201, 330, 'Перемещение товара из розницы на оптовый склад (учет в ценах продажи)', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28128202, 521, 'Перемещение товаров из розницы на оптовый склад (суммовой учет в ценах прихода)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28128203, 522, 'Перемещение товаров из розницы на оптовый склад (суммовой учет в ценах реализации)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28163100, 505, 'Приход товаров на оптовый склад (суммовой учет)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28179100, 355, 'Инвентаризация ТМЦ (учет в ЦП)', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28179101, 497, 'Инвентаризация ТМЦ (учет в ЦП, без корректировки НДС по излишкам)', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28179102, 553, 'Инвентаризация товаров на оптовом складе (суммовой учет)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28179103, 554, 'Инвентаризация товаров на оптовом складе (суммовой учет, без корректировки НДС по излишкам)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228100, 327, 'Переданы товары с оптового склада в розницу (учет в ценах прихода)', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228101, 38, 'Переданы товары с оптового склада в розницу (учет в ценах продажи)', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228102, 517, 'Перемещение товаров с оптового склада в розницу (суммовой учет в ценах прихода)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228103, 518, 'Перемещение товаров с оптового склада в розницу (суммовой учет в ценах реализации)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228200, 335, 'Перемещение товаров между розничными отделами (учет в ценах прихода)', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228201, 336, 'Перемещение товаров между розничными отделами (учет в ценах продажи)', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228202, 519, 'Перемещение товаров между розничными отделами (суммовой учет в ценах прихода)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228203, 520, 'Перемещение товаров между розничными отделами (суммовой учет в ценах продажи)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228500, 532, 'Переоценка товаров в рознице (учет в ценах реализации, без корректировки НДС)', '', 1, 6, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228501, 533, 'Переоценка товаров в рознице (учет в ценах реализации, с корректировкой НДС)', '', 1, 6, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228502, 546, 'Переоценка товаров в рознице (суммовой учет в ценах реализации, с корректировкой НДС)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28228503, 547, 'Переоценка товаров в рознице (суммовой учет в ценах реализации, без корректировки НДС)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28263100, 485, 'Оприходованы товары от поставщика в розницу (учет в ценах прихода)', '', 1, 3, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28263101, 486, 'Оприходованы товары от поставщика в розницу (учет в ценах реализации)', '', 1, 3, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28263102, 507, 'Приход товаров в розницу (суммовой учет в ценах прихода)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28263103, 508, 'Приход товаров в розницу (суммовой учет в ценах реализации)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28279100, 496, 'Инвентаризация ТМЦ (учет в ЦР)', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28279101, 499, 'Инвентаризация ТМЦ (учет в ЦР, без корректировки НДС)', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28279102, 555, 'Инвентаризация товаров в рознице (суммовой учет в ценах прихода)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28279103, 556, 'Инвентаризация товаров в рознице (суммовой учет в ценах прихода, без корректировки НДС по излишкам)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28279104, 557, 'Инвентаризация товаров в рознице (суммовой учет в ценах реализации)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28279105, 558, 'Инвентаризация товаров в рознице (суммовой учет в ценах реализации, без корректировки НДС по излишкам)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28428400, 523, 'Перемещение тары (суммовой учет)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (28463100, 506, 'Приход тары (суммовой учет)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (30170200, 39, 'Поступили денежные средства за проданный товар в рознице (учет в ценах прихода)', '', 1, 5, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (30170201, 270, 'Поступили денежные средства за проданный товар в рознице (учет в ценах продажи)', '', 1, 5, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (30170202, 514, 'Розничная продажа товара (суммовой учет в ценах прихода)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (30170203, 515, 'Розничная продажа товара (суммовой учет в ценах реализации)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (30170204, 614, 'Розничная продажа золота (суммовой учет в ценах прихода)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (30170205, 615, 'Розничная продажа золота (суммовой учет в ценах реализации)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (31133300, 492, 'Зачислены на расчетный счет денежные средства, находящиеся в пути', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (31137701, 258, 'Поступила оплата за реализованные необоротные активы', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (31137702, 71, 'Поступила оплата за реализованные запасы, арендная плата', '', 1, 4, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (31233300, 402, 'Зачислена на валютный счет приобретенная валюта (операционная деятельность)', '', 1, 20, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (31233301, 416, 'Зачислена на валютный счет приобретенная валюта (финансовая деятельность)', '', 1, 20, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (33331100, 552, 'Перечислено комиссионное вознаграждение банку', '', 1, 20, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (33331101, 100000002, 'Перечислены денежные средства на покупку валюты', '', 0, 0, 0, 'ПО-380245-333311');
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (36170200, 513, 'Отгружен товар покупателю (оптовая торговля, суммовой учет)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (37101311, 582, 'Отражены расходы будущих периодов (арендная плата, прочие затраты)', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (37701713, 559, 'Отражен доход от сдачи в аренду необоротных активов', '', 1, 29, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (44367100, 524, 'Начислены дивиденды с удержанием 15% подоходного налога', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (46040000, 125, 'Дополнительный выпуск акций за счет начисленных дивидендов', '', 1, 13, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (60131101, 548, 'Погашен краткосрочный кредит в национальной валюте', '', 1, 18, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (60131102, 549, 'Списаны гарантии с забалансового счета при полном погашении кредита', '', 1, 18, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (63128100, 509, 'Возврат товара поставщику с оптового склада (суммовой учет)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (63128200, 487, 'Возвращен товар поставщику из розницы (учет в ценах прихода )', '', 1, 3, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (63128201, 488, 'Возвращен товар поставщику из розницы (учет в ценах продажи)', '', 1, 3, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (63128202, 511, 'Возврат товара поставщику из розницы (суммовой учет в ценах прихода)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (63128203, 512, 'Возврат товара поставщику из розницы (суммовой учет в ценах реализации)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (63128400, 510, 'Возврат тары поставщику (суммовой учет)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (63131100, 9, 'Оплата за товар, услуги', '', 1, 3, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (63131104, 613, 'Оплата за необоротные активы', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (64101311, 73, 'Перечислен подоходный налог', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (64110311, 451, 'Оплачен налог на транспорт', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (64111311, 453, 'Оплачен сбор на развитие виноградарства', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (64112311, 449, 'Оплачены финансовые санкции (начисленные налоговыми органами)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (64209311, 100000006, 'Перечислен военный сбор', NULL, 0, 25, 1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (64231100, 345, 'Перечислено в бюджет возмещение ущерба', '', 1, 17, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65101311, 74, 'Перечислены взносы в Пенсионный фонд на фонд (начисления на зарплату 32%)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65102311, 534, 'Перечислены взносы в Пенсионный фонд на фонд (начисления на зарплату 4%)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65103311, 535, 'Перечислены взносы в Пенсионный фонд на фонд (удержания с зарплаты 1-5%)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65105311, 460, 'Перечислен сбор в Пенсионный фонд с купли-продажи ювелирных изделий', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65106311, 536, 'Перечислен сбор в Пенсионный фонд с операций по отчуждению автомобилей', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65107311, 537, 'Перечислен сбор в Пенсионный фонд с производителей и импортеров табачных изделий', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65131100, 400, 'Начислен и перечислен сбор в Пенсионный фонд на покупку валюты', '', 1, 20, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65201311, 75, 'Перечислены взносы в Фонд социального страхования (начисление на фонд оплаты труда 2,9%)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65202311, 539, 'Перечислены взносы в Фонд социального страхования (начисление на фонд оплаты труда 0,7%)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65203311, 540, 'Перечислены взносы в Фонд социального страхования (удержание из фонда оплаты труда 0,5%)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65301311, 76, 'Перечислены взносы в Фонд занятости (начисление на фонд оплаты труда 1,9%)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (65302311, 538, 'Перечислены взносы в Фонд занятости (удержание из фонда оплаты труда 0,5%)', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (66130100, 608, 'Выдана или депонирована заработная плата (Кадры и Зарплата)', '', 1, 31, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (66165100, 607, 'Начисление (удержание) взносов на страхование', '', 1, 31, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (66230100, 610, 'Выдана депонированная заработная плата (Кадры и Зарплата)', '', 1, 31, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (68401311, 375, 'Перечислены проценты за краткосрочный кредит в национальной валюте', '', 1, 18, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (68501311, 78, 'Перечислены Профсоюзные взносы', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (68531101, 578, 'Перечислена арендная плата арендодателю', '', 1, 1, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (70430100, 328, 'Возврат товара покупателем в рознице (учет в ценах прихода)', '', 1, 5, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (70430101, 43, 'Возврат товара покупателем в рознице (учет в ценах продажи)', '', 1, 5, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (70430102, 526, 'Возврат товара от покупателя из розницы (суммовой учет в ценах прихода)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (70430103, 527, 'Возврат товара от покупателя из розницы (суммовой учет в ценах реализации)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (70436100, 525, 'Возврат товара от покупателя (оптовая торговля, суммовой учет)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (81166103, 606, 'Начислены выплаты и удержания (заработная плата, больничные, компенсации)', '', 1, 31, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (84039000, 585, 'Списаны расходы будущих периодов на затраты (арендная плата, лицензии)', '', 1, 29, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (84039001, 594, 'Списаны расходы будущих периодов на затраты (налоги и сборы)', '', 1, 29, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (84039002, 595, 'Списаны расходы будущих периодов на затраты (прочие затраты)', '', 1, 29, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (84064110, 450, 'Начислен налог на транспорт', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (84064111, 452, 'Начислен сбор на развитие виноградарства', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (84064112, 448, 'Начислены финансовые санкции налоговыми органами', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (84068501, 577, 'Отражены расходы на арендную плату у арендатора', '', 1, 29, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (90064109, 100000001, 'Коммунальный налог', NULL, 1, 31, 0, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (92063100, 281, 'Ремонт необоротных активов (ОС, НМА, прочие) (услуга от поставщика)', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (93020100, 489, 'Списание ТМЦ на хозяйственную деятельность', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (93020101, 490, 'Списание ТМЦ на прочие нужды или по порче', '', 1, 27, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94628100, 46, 'Переоценка ТМЦ в оптовой торговле (без корректировки НДС)', '', 1, 6, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94628101, 529, 'Переоценка ТМЦ в оптовой торговле (с корректировкой НДС)', '', 1, 6, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94628102, 541, 'Переоценка товаров (оптовая торговля, суммовой учет, с корректировкой НДС)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94628103, 542, 'Переоценка товаров (оптовая торговля, суммовой учет, без корректировки НДС)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94628200, 530, 'Переоценка товаров в рознице (учет в ценах прихода, без корректировки НДС)', '', 1, 6, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94628201, 531, 'Переоценка товаров в рознице (учет в ценах прихода, с корректировкой НДС)', '', 1, 6, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94628202, 544, 'Переоценка товаров в рознице (суммовой учет в ценах прихода, с корректировкой НДС)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94628203, 545, 'Переоценка товаров в рознице (суммовой учет в ценах прихода, без корректировки НДС)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94928100, 589, 'Списание товаров с оптового склада', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94928200, 591, 'Списание товаров из розницы (учет в ценах прихода)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (94928201, 592, 'Списание товаров из розницы (учет в ценах реализации)', '', 1, 28, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (95168401, 374, 'Начислены проценты за краткосрочный кредит в национальной валюте', '', 1, 18, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (97610200, 216, 'Ликвидация необоротных активов вследствие полного износа', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (97610201, 221, 'Ликвидация необоротных активов по самостоятельному решению', '', 1, 10, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (641063110, 543, 'Перечислен налог на прибыль', '', 1, 25, -1, NULL);
INSERT dbo.r_GOpers(GOperID, ChID, GOperName, Notes, WasChanged, GOperCID, RevID, RevName) VALUES (641063111, 612, 'Перечислен налог на дивиденды', '', 1, 25, -1, NULL);
