INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (0, 0, 'Нет категории ОС', '');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (101, 1, 'Земельные участки', '15200');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (102, 2, 'Капитальные затраты на улучшение земель', '15200');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (103, 3, 'Здания и сооружения', '15100');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (104, 4, 'Машины и оборудование', '15200');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (105, 5, 'Транспортные средства', '15200');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (106, 6, 'Инструменты, приборы и инвентарь', '15200');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (107, 7, 'Рабочий и продуктивный скот', '15500');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (108, 8, 'Многолетние насаждения', '15200');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (109, 9, 'Прочие основные средства', '15200');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (111, 10, 'Библиотечные фонды', '15300');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (112, 11, 'Малоценные необоротные материальные активы', '15300');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (113, 12, 'Временные  (нетитульные) сооружения', '15300');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (114, 13, 'Природные ресурсы', '15300');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (115, 14, 'Инвентарная тара', '15300');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (116, 15, 'Предметы проката', '15300');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (117, 16, 'Прочие необоротные материальные активы', '15300');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (121, 17, 'Права пользования природными ресурсами', '15400');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (122, 18, 'Права пользования имуществом', '15400');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (123, 19, 'Права на знаки для товаров и услуг', '15400');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (124, 20, 'Права на объекты промышленной собственности', '15400');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (125, 21, 'Авторские и смежные с ними права', '15400');
INSERT dbo.r_AssetC(ACatID, ChID, ACatName, Notes) VALUES (127, 22, 'Прочие нематериальные активы', '15400');
