INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Общие\Отчеты\Акт Сверки взаимных расчетов.fr3', 'Акт сверки взаимных расчетов', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Общие\Отчеты\Баланс - Предприятие.fr3', 'Баланс - Предприятие', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Торговля\Отчеты\Баланс - Заказ внешний.fr3', 'Баланс - Заказ внешний', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Торговля\Отчеты\Баланс - Заказ внутренний.fr3', 'Баланс - Заказ внутренний', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Торговля\Отчеты\Баланс - Товар заказов.fr3', 'Баланс - Товар заказов', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Торговля\Отчеты\Баланс - Товар.fr3', 'Баланс - Товар', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Торговля\Отчеты\Баланс - ЭККА.fr3', 'Баланс - ЭККА', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Торговля\Отчеты\Движение товара - Внутреннее.fr3', 'Движение товара - Внутреннее', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Торговля\Отчеты\Движение товара - Предприятие.fr3', 'Движение товара - Предприятие', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Торговля\Отчеты\Движение товара - ЭККА.fr3', 'Движение товара - ЭККА', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (11000, 'Торговля\Отчеты\Движение товара.fr3', 'Движение товара', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (12000, 'Общие\Отчеты\Баланс - Предприятие.fr3', 'Баланс - Предприятие', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (12000, 'Финансы\Отчеты\Баланс - Валюта.fr3', 'Баланс - Валюта', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (12000, 'Финансы\Отчеты\Баланс - Валютный счет (Финансы).fr3', 'Баланс - Валютный счет (Финансы)', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (12000, 'Финансы\Отчеты\Баланс - Касса.fr3', 'Баланс - Касса', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (12000, 'Финансы\Отчеты\Баланс - Служащий.fr3', 'Баланс - Служащий', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Банк\Отчеты\Баланс - Валютный счет (Банк).fr3', 'Баланс - Валютный счет', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Банк\Отчеты\Баланс - Расчетный счет.fr3', 'Баланс - Расчетный счет', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Общие\Отчеты\Баланс - Касса.fr3', 'Баланс - Касса', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Общие\Отчеты\Баланс - Предприятие (Бухгалтерия).fr3', 'Баланс - Предприятие (Бухгалтерия)', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Общие\Отчеты\Баланс - Служащий (Бухгалтерия).fr3', 'Баланс - Служащий (Бухгалтерия)', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Общие\Отчеты\Реестр полученных и выданных налоговых накладных.fr3', 'Реестр полученных и выданных налоговых накладных', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Баланс.fr3', 'Баланс', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Главная Книга.fr3', 'Главная Книга', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Журнал Операций (Подробно).fr3', 'Журнал Операций (Подробно)', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Журнал Операций (Полный).fr3', 'Журнал Операций (Полный)', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Журнал Операций.fr3', 'Журнал Операций', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Журнал регистрации приходных и расходных кассовых документов.fr3', 'Журнал регистрации приходных и расходных кассовых документов', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Журнал-Ордер (Полный).fr3', 'Журнал-Ордер (Полный)', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Журнал-Ордер.fr3', 'Журнал-Ордер', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Кассовая Книга.fr3', 'Кассовая Книга', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Оборотно-Сальдовая Ведомость.fr3', 'Оборотно-Сальдовая Ведомость', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\Отчеты\Шахматка.fr3', 'Шахматка', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\ТМЦ\Отчеты\Баланс - ТМЦ.fr3', 'Баланс - ТМЦ', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\ТМЦ\Отчеты\Движение ТМЦ - Внутреннее.fr3', 'Движение ТМЦ - Внутреннее', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\ТМЦ\Отчеты\Движение ТМЦ - Предприятие.fr3', 'Движение ТМЦ - Предприятие', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Бухгалтерия\ТМЦ\Отчеты\Движение ТМЦ.fr3', 'Движение ТМЦ', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14000, 'Общие\Отчеты\Баланс - Предприятие.fr3', 'Баланс - Предприятие', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14010, 'Бухгалтерия\Банк\Отчеты\Баланс - Валютный счет (Банк).fr3', 'Баланс - Валютный счет', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14010, 'Бухгалтерия\Банк\Отчеты\Баланс - Расчетный счет.fr3', 'Баланс - Расчетный счет', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (14010, 'Общие\Отчеты\Баланс - Предприятие.fr3', 'Баланс - Предприятие', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Бухгалтерия\Отчеты\Баланс.fr3', 'Баланс', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Бухгалтерия\Отчеты\Главная Книга.fr3', 'Главная Книга', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Бухгалтерия\Отчеты\Журнал Операций (Подробно).fr3', 'Журнал Операций (Подробно)', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Бухгалтерия\Отчеты\Журнал Операций (Полный).fr3', 'Журнал Операций (Полный)', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Бухгалтерия\Отчеты\Журнал Операций.fr3', 'Журнал Операций', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Бухгалтерия\Отчеты\Журнал-Ордер (Полный).fr3', 'Журнал-Ордер (Полный)', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Бухгалтерия\Отчеты\Журнал-Ордер.fr3', 'Журнал-Ордер', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Бухгалтерия\Отчеты\Кассовая Книга.fr3', 'Кассовая Книга', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Бухгалтерия\Отчеты\Оборотно-Сальдовая Ведомость.fr3', 'Оборотно-Сальдовая Ведомость', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Бухгалтерия\Отчеты\Шахматка.fr3', 'Шахматка', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Кадры и Зарплата\Отчеты\Баланс - Кадровое состояние.fr3', 'Баланс - Кадровое состояние', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Кадры и Зарплата\Отчеты\Баланс - Служащий (Кадры и Зарплата).fr3', 'Баланс - Служащий (Кадры и Зарплата)', NULL, NULL, 0);
INSERT dbo.z_AppPrints(AppCode, FileName, FileDesc, FileDate, BlobValue, UseBlob) VALUES (15000, 'Общие\Документы\Экспорт электронной отчетности.fr3', 'Экспорт электронной отчетности', NULL, NULL, 0);
