INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (0, 0, 'Нет страны', 'Немає країни', '0', '0', NULL);
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (4, 100000015, 'Афганистан', 'Афганістан', 'AF', 'AFG', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (8, 100000005, 'Албания', 'Албанія', 'AL', 'ALB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (10, 100000011, 'Антарктика', 'Антарктика', 'AQ', 'ATA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (12, 100000006, 'Алжир', 'Алжир', 'DZ', 'DZA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (16, 100000007, 'Американское Самоа', 'Американське Самоа', 'AS', 'ASM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (20, 100000010, 'Андорра', 'Андорра', 'AD', 'AND', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (24, 100000009, 'Ангола', 'Ангола', 'AO', 'AGO', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (28, 100000012, 'Антигуа и Барбуда', 'Антигуа і Барбуда', 'AG', 'ATG', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (31, 100000003, 'Азербайджан', 'Азербайджан', 'AZ', 'AZE', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (32, 100000013, 'Аргентина', 'Аргентина', 'AR', 'ARG', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (36, 100000001, 'Австралия', 'Австралія', 'AU', 'AUS', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (40, 100000002, 'Австрия', 'Австрія', 'AT', 'AUT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (44, 100000016, 'Багамские острова', 'Багамські острови', 'BS', 'BHS', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (48, 100000019, 'Бахрейн', 'Бахрейн', 'BH', 'BHR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (50, 100000017, 'Бангладеш', 'Бангладеш', 'BD', 'BGD', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (51, 100000042, 'Армения', 'Вірменія', 'AM', 'ARM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (52, 100000018, 'Барбадос', 'Барбадос', 'BB', 'BRB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (56, 100000021, 'Бельгия', 'Бельгія', 'BE', 'BEL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (60, 100000023, 'Бермудские острова', 'Бермудські острови', 'BM', 'BMU', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (64, 100000035, 'Бутан', 'Бутан', 'BT', 'BTN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (68, 100000026, 'Боливия', 'Болівія', 'BO', 'BOL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (70, 100000028, 'Босния и Герцеговина', 'Боснія і Герцеговина', 'BA', 'BIH', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (72, 100000029, 'Ботсвана', 'Ботсвана', 'BW', 'BWA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (74, 100000155, 'Остров Буве', 'Острів Буве', 'BV', 'BVT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (76, 100000030, 'Бразилия', 'Бразілія', 'BR', 'BRA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (84, 100000020, 'Белиз', 'Беліз', 'BZ', 'BLZ', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (86, 100000031, 'Британская территория в Индийском океане', 'Британська територія в Індійському океані', 'IO', 'IOT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (90, 100000204, 'Соломоновы острова', 'Соломонові острови', 'SB', 'SLB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (92, 100000040, 'Виргинские острова (Брит.)', 'Віргінські острови (Брит.)', 'VG', 'VGB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (96, 100000032, 'Бруней-Даруссалам', 'Бруней-Даруссалам', 'BN', 'BRN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (100, 100000025, 'Болгария', 'Болгарія', 'BG', 'BGR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (104, 100000140, 'Мьянма', 'М''янма', 'MM', 'MMR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (108, 100000034, 'Бурунди', 'Бурунді', 'BI', 'BDI', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (112, 100000024, 'Беларусь', 'Білорусь', 'BY', 'BLR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (116, 100000089, 'Камбоджа', 'Камбоджа', 'KH', 'KHM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (120, 100000090, 'Камерун', 'Камерун', 'CM', 'CMR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (124, 100000091, 'Канада', 'Канада', 'CA', 'CAN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (132, 100000086, 'Кабо-Верде', 'Кабо-Верде', 'CV', 'CPV', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (136, 100000088, 'Каймановы острова', 'Кайманові острови', 'KY', 'CYM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (140, 100000239, 'Центральноафриканская Республика', 'Центральноафриканська Республіка', 'CF', 'CAF', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (144, 100000247, 'Шри Ланка', 'Шрі-Ланка', 'LK', 'LKA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (148, 100000240, 'Чад', 'Чад', 'TD', 'TCD', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (152, 100000242, 'Чили', 'Чілі', 'CL', 'CHL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (156, 100000095, 'Китай', 'Китай', 'CN', 'CHN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (158, 100000212, 'Тайвань, Провинция Китая', 'Тайвань, Провінція Китаю', 'TW', 'TWN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (162, 100000159, 'Остров Рождества', 'Острів Різдва', 'CX', 'CXR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (166, 100000098, 'Кокосовые (Килинг) острова', 'Кокосові (Кілінг) острови', 'CC', 'CCK', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (170, 100000100, 'Колумбия', 'Колумбія', 'CO', 'COL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (174, 100000101, 'Кладовой', 'Комори', 'KM', 'COM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (175, 100000122, 'Майотта', 'Майотта', 'YT', 'MYT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (178, 100000102, 'Конго', 'Конго', 'CG', 'COG', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (184, 100000161, 'Острова Кука', 'Острови Кука', 'CK', 'COK', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (188, 100000105, 'Коста-Рика', 'Коста-Ріка', 'CR', 'CRI', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (191, 100000238, 'Хорватия', 'Хорватія', 'HR', 'HRV', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (192, 100000107, 'Куба', 'Куба', 'CU', 'CUB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (196, 100000096, 'Кипр', 'Кіпр', 'CY', 'CYP', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (203, 100000241, 'Чехия', 'Чехія', 'CZ', 'CZE', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (204, 100000022, 'Бенин', 'Бенін', 'BJ', 'BEN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (208, 100000061, 'Дания', 'Данія', 'DK', 'DNK', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (212, 100000064, 'Доминика', 'Домініка', 'DM', 'DMA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (214, 100000065, 'Доминиканская Республика', 'Домініканська Республіка', 'DO', 'DOM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (218, 100000066, 'Эквадор', 'Еквадор', 'EC', 'ECU', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (222, 100000182, 'Сальвадор', 'Сальвадор', 'SV', 'SLV', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (226, 100000067, 'Экваториальная Гвинея', 'Екваторіальна Гвінея', 'GQ', 'GNQ', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (231, 100000070, 'Эфиопия', 'Ефіопія', 'ET', 'ETH', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (232, 100000068, 'Эритрея', 'Еритрея', 'ER', 'ERI', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (233, 100000069, 'Эстония', 'Естонія', 'EE', 'EST', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (234, 100000229, 'Фарерские острова', 'Фарерські острови', 'FO', 'FRO', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (238, 100000233, 'Фолклендские (Мальвинские) острова', 'Фолклендські (Мальвінські) острови', 'FK', 'FLK', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (239, 100000171, 'Южная Джорджия и Южные Сандвичевы острова', 'Південна Джорджія і Південні Сандвічеві острови', 'GS', 'SGS', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (242, 100000230, 'Фиджи', 'Фіджі', 'FJ', 'FJI', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (246, 100000232, 'Финляндия', 'Фінляндія', 'FI', 'FIN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (248, 100000004, 'Аландские острова', 'Аландські острови', 'AX', 'ALA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (250, 100000234, 'Франция', 'Франція', 'FR', 'FRA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (254, 100000235, 'Французская Гвинея', 'Французька Гвіана', 'GF', 'GUF', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (258, 100000236, 'Французская Полинезия', 'Французька Полінезія', 'PF', 'PYF', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (260, 100000237, 'Французские Южные территории', 'Французькі Південні території', 'TF', 'ATF', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (262, 100000063, 'Джибути', 'Джібуті', 'DJ', 'DJI', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (266, 100000049, 'Габон', 'Габон', 'GA', 'GAB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (268, 100000048, 'Грузия', 'Грузія', 'GE', 'GEO', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (270, 100000051, 'Гамбия', 'Гамбія', 'GM', 'GMB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (275, 100000165, 'Палестина', 'Палестина', 'PS', 'PSE', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (276, 100000148, 'Германия', 'Німеччина', 'DE', 'DEU', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (288, 100000044, 'Гана', 'Гана', 'GH', 'GHA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (292, 100000057, 'Гибралтар', 'Гібралтар', 'GI', 'GIB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (296, 100000097, 'Кирибати', 'Кірібаті', 'KI', 'KIR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (300, 100000047, 'Греция', 'Греція', 'GR', 'GRC', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (304, 100000059, 'Гренландия', 'Гренландія', 'GL', 'GRL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (308, 100000058, 'Гренада', 'Гренада', 'GD', 'GRD', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (312, 100000052, 'Гваделупа', 'Гваделупа', 'GP', 'GLP', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (316, 100000060, 'Гуам', 'Гуам', 'GU', 'GUM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (320, 100000053, 'Гватемала', 'Гватемала', 'GT', 'GTM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (324, 100000054, 'Гвинея', 'Гвінея', 'GN', 'GIN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (328, 100000050, 'Гайана', 'Гайана', 'GY', 'GUY', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (332, 100000043, 'Гаити', 'Гаїті', 'HT', 'HTI', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (334, 100000156, 'Остров Герд и острова Макдоналд', 'Острів Герд і острови Макдоналд', 'HM', 'HMD', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (336, 100000189, 'Святой Престол (Государство-город Ватикан)', 'Святий Престол (Держава-місто Ватикан)', 'VA', 'VAT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (340, 100000045, 'Гондурас', 'Гондурас', 'HN', 'HND', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (344, 100000046, 'Гонконг', 'Гонконг', 'HK', 'HKG', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (348, 100000224, 'Венгрия', 'Угорщина', 'HU', 'HUN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (352, 100000082, 'Исландия', 'Ісландія', 'IS', 'ISL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (356, 100000077, 'Индия', 'Індія', 'IN', 'IND', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (360, 100000078, 'Индонезия', 'Індонезія', 'ID', 'IDN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (364, 100000080, 'Иран, Исламская Республика', 'Іран, Ісламська Республіка', 'IR', 'IRN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (368, 100000079, 'Ирак', 'Ірак', 'IQ', 'IRQ', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (372, 100000081, 'Ирландия', 'Ірландія', 'IE', 'IRL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (376, 100000076, 'Израиль', 'Ізраїль', 'IL', 'ISR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (380, 100000084, 'Италия', 'Італія', 'IT', 'ITA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (384, 100000106, 'Кот-Д''Ивуар', 'Кот-Д''Івуар', 'CI', 'CIV', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (388, 100000248, 'Ямайка', 'Ямайка', 'JM', 'JAM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (392, 100000249, 'Япония', 'Японія', 'JP', 'JPN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (398, 100000087, 'Казахстан', 'Казахстан', 'KZ', 'KAZ', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (400, 100000085, 'Иордания', 'Йорданія', 'JO', 'JOR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (404, 100000093, 'Кения', 'Кенія', 'KE', 'KEN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (408, 100000103, 'Корейская Народно-Демократическая Республика', 'Корейська Народно-Демократична Республіка', 'KP', 'PRK', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (410, 100000104, 'Корея, Республика', 'Корея, Республіка', 'KR', 'KOR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (414, 100000108, 'Кувейт', 'Кувейт', 'KW', 'KWT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (417, 100000094, 'Кыргызстан', 'Киргизстан', 'KG', 'KGZ', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (418, 100000110, 'Лаосская Народно-Демократическая Республика', 'Лаоська Народно-Демократична Республіка', 'LA', 'LAO', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (422, 100000115, 'Ливан', 'Ліван', 'LB', 'LBN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (426, 100000112, 'Лесото', 'Лесото', 'LS', 'LSO', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (428, 100000111, 'Латвия', 'Латвія', 'LV', 'LVA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (430, 100000114, 'Либерия', 'Ліберія', 'LR', 'LBR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (434, 100000116, 'Ливия', 'Лівія', 'LY', 'LBY', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (438, 100000117, 'Лихтенштейн', 'Ліхтенштейн', 'LI', 'LIE', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (440, 100000113, 'Литва', 'Литва', 'LT', 'LTU', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (442, 100000118, 'Люксембург', 'Люксембург', 'LU', 'LUX', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (446, 100000123, 'Макао', 'Макао', 'MO', 'MAC', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (450, 100000121, 'Мадагаскар', 'Мадагаскар', 'MG', 'MDG', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (454, 100000124, 'Малави', 'Малаві', 'MW', 'MWI', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (458, 100000125, 'Малайзия', 'Малайзія', 'MY', 'MYS', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (462, 100000128, 'Мальдивы', 'Мальдіви', 'MV', 'MDV', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (466, 100000126, 'Малые', 'Малі', 'ML', 'MLI', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (470, 100000129, 'Мальта', 'Мальта', 'MT', 'MLT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (474, 100000131, 'Мартиника', 'Мартініка', 'MQ', 'MTQ', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (478, 100000120, 'Мавритания', 'Мавританія', 'MR', 'MRT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (480, 100000119, 'Маврикий', 'Маврікій', 'MU', 'MUS', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (484, 100000133, 'Мексика', 'Мексика', 'MX', 'MEX', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (492, 100000137, 'Монако', 'Монако', 'MC', 'MCO', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (496, 100000138, 'Монголия', 'Монголія', 'MN', 'MNG', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (498, 100000136, 'Молдова, Республика', 'Молдова, Республіка', 'MD', 'MDA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (499, 100000243, 'Черногория', 'Чорногорія', 'ME', 'MNE', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (500, 100000139, 'Монтсеррат', 'Монтсеррат', 'MS', 'MSR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (504, 100000130, 'Марокко', 'Марокко', 'MA', 'MAR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (508, 100000135, 'Мозамбик', 'Мозамбік', 'MZ', 'MOZ', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (512, 100000154, 'Оман', 'Оман', 'OM', 'OMN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (516, 100000141, 'Намибия', 'Намібія', 'NA', 'NAM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (520, 100000142, 'Науру', 'Науру', 'NR', 'NRU', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (524, 100000143, 'Непал', 'Непал', 'NP', 'NPL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (528, 100000146, 'Нидерланды', 'Нідерланди', 'NL', 'NLD', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (531, 100000109, 'Кюрасао', 'Кюрасао', 'CW', 'CUW', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (533, 100000014, 'Аруба', 'Аруба', 'AW', 'ABW', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (534, 100000200, 'Синт-Мартен (Нидерландская часть)', 'Сінт-Мартен (Нідерландська частина)', 'SX', 'SXM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (535, 100000027, 'Бонайре, Синт-Эстатиус и Саба', 'Бонайре, Сінт-Естатіус і Саба', 'BQ', 'BES', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (540, 100000151, 'Новая Каледония', 'Нова Каледонія', 'NC', 'NCL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (548, 100000036, 'Вануату', 'Вануату', 'VU', 'VUT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (554, 100000150, 'Новая Зеландия', 'Нова Зеландія', 'NZ', 'NZL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (558, 100000147, 'Никарагуа', 'Нікарагуа', 'NI', 'NIC', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (562, 100000144, 'Нигер', 'Нігер', 'NE', 'NER', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (566, 100000145, 'Нигерия', 'Нігерія', 'NG', 'NGA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (570, 100000149, 'Ниуэ', 'Ніуе', 'NU', 'NIU', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (574, 100000158, 'Остров Норфолк', 'Острів Норфолк', 'NF', 'NFK', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (578, 100000152, 'Норвегия', 'Норвегія', 'NO', 'NOR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (580, 100000173, 'Северные Марианские острова', 'Північні Маріанські острови', 'MP', 'MNP', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (581, 100000127, 'Малые удаленные острова США', 'Малі віддалені острови США', 'UM', 'UMI', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (583, 100000134, 'Микронезия, Федеративные Штаты', 'Мікронезія, Федеративні Штати', 'FM', 'FSM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (584, 100000132, 'Маршалловы острова', 'Маршаллові острови', 'MH', 'MHL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (585, 100000164, 'Палау', 'Палау', 'PW', 'PLW', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (586, 100000163, 'Пакистан', 'Пакистан', 'PK', 'PAK', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (591, 100000166, 'Панама', 'Панама', 'PA', 'PAN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (598, 100000167, 'Папуа-Новая Гвинея', 'Папуа-Нова Гвінея', 'PG', 'PNG', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (600, 100000168, 'Парагвай', 'Парагвай', 'PY', 'PRY', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (604, 100000169, 'Перу', 'Перу', 'PE', 'PER', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (608, 100000231, 'Филиппины', 'Філіппіни', 'PH', 'PHL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (612, 100000174, 'Питкэрн', 'Піткерн', 'PN', 'PCN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (616, 100000175, 'Польша', 'Польща', 'PL', 'POL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (620, 100000176, 'Португалия', 'Португалія', 'PT', 'PRT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (624, 100000055, 'Гвинея-Бисау', 'Гвінея-Бісау', 'GW', 'GNB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (626, 100000214, 'Тимор-Лешти', 'Тімор-Лешті', 'TL', 'TLS', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (630, 100000177, 'Пуэрто-Рико', 'Пуерто-Ріко', 'PR', 'PRI', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (634, 100000092, 'Катар', 'Катар', 'QA', 'QAT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (638, 100000178, 'Реюньон', 'Реюньйон', 'RE', 'REU', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (642, 100000181, 'Румыния', 'Румунія', 'RO', 'ROU', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (643, 100000179, 'Российская Федерация', 'Російська Федерація', 'RU', 'RUS', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (646, 100000180, 'Руанда', 'Руанда', 'RW', 'RWA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (652, 100000191, 'Сен-Бартелеми', 'Сен-Бартелемі', 'BL', 'BLM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (654, 100000160, 'Остров Святой Елены', 'Острів Святої Єлени', 'SH', 'SHN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (659, 100000196, 'Сент-Китс и Невис', 'Сент-Кітс і Невіс', 'KN', 'KNA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (660, 100000008, 'Ангилья', 'Ангілья', 'AI', 'AIA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (662, 100000197, 'Сент-Люсия', 'Сент-Люсія', 'LC', 'LCA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (663, 100000193, 'Сен-Мартен (Французская Часть)', 'Сен-Мартен (Французька Частина)', 'MF', 'MAF', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (666, 100000194, 'Сен-Пьер и Микелон', 'Сен-П''єр і Мікелон', 'PM', 'SPM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (670, 100000195, 'Сент-Винсент и Гренадины', 'Сент-Вінсент і Гренадіни', 'VC', 'VCT', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (674, 100000184, 'Сан-Марино', 'Сан-Маріно', 'SM', 'SMR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (678, 100000185, 'Сан-Томе и Принсипи', 'Сан-Томе і Прінсіпі', 'ST', 'STP', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (680, 100000186, 'Сарк', 'Сарк', '-', '-', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (682, 100000187, 'Саудовская Аравия', 'Саудівська Аравія', 'SA', 'SAU', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (686, 100000192, 'Сенегал', 'Сенегал', 'SN', 'SEN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (688, 100000198, 'Сербия', 'Сербія', 'RS', 'SRB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (690, 100000190, 'Сейшельские острова', 'Сейшельські острови', 'SC', 'SYC', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (694, 100000209, 'Сьерра-Леоне', 'Сьєрра-Леоне', 'SL', 'SLE', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (702, 100000199, 'Сингапур', 'Сінгапур', 'SG', 'SGP', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (703, 100000202, 'Словакия', 'Словаччина', 'SK', 'SVK', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (704, 100000039, 'Вьетнам', 'В''єтнам', 'VN', 'VNM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (705, 100000203, 'Словения', 'Словенія', 'SI', 'SVN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (706, 100000205, 'Сомали', 'Сомалі', 'SO', 'SOM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (710, 100000170, 'Южная Африка', 'Південна Африка', 'ZA', 'ZAF', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (716, 100000075, 'Зимбабве', 'Зімбабве', 'ZW', 'ZWE', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (724, 100000083, 'Испания', 'Іспанія', 'ES', 'ESP', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (728, 100000172, 'Южный Судан', 'Південний Судан', 'SS', 'SSD', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (729, 100000206, 'Судан', 'Судан', 'SD', 'SDN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (732, 100000074, 'Западная Сахара', 'Західна Сахара', 'EH', 'ESH', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (740, 100000207, 'Суринам', 'Сурінам', 'SR', 'SUR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (744, 100000246, 'Шпицберген и Ян-Майен', 'Шпіцберген та Ян-Маєн', 'SJ', 'SJM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (748, 100000188, 'Свазиленд', 'Свазіленд', 'SZ', 'SWZ', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (752, 100000245, 'Швеция', 'Швеція', 'SE', 'SWE', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (756, 100000244, 'Швейцария', 'Швейцарія', 'CH', 'CHE', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (760, 100000201, 'Сирийская Арабская Республика', 'Сирійська Арабська Республіка', 'SY', 'SYR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (762, 100000210, 'Таджикистан', 'Таджикистан', 'TJ', 'TJK', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (764, 100000211, 'Таиланд', 'Таїланд', 'TH', 'THA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (768, 100000215, 'Того', 'Того', 'TG', 'TGO', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (772, 100000216, 'Токелау', 'Токелау', 'TK', 'TKL', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (776, 100000217, 'Тонга', 'Тонга', 'TO', 'TON', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (780, 100000218, 'Тринидад и Тобаго', 'Трінідад і Тобаго', 'TT', 'TTO', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (784, 100000153, 'Объединенные Арабские Эмираты', 'Об''єднані Арабські Емірати', 'AE', 'ARE', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (788, 100000220, 'Тунис', 'Туніс', 'TN', 'TUN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (792, 100000221, 'Турция', 'Туреччина', 'TR', 'TUR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (795, 100000222, 'Туркменистан', 'Туркменістан', 'TM', 'TKM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (796, 100000162, 'Острова Теркс и Кайкос', 'Острови Теркс і Кайкос', 'TC', 'TCA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (798, 100000219, 'Тувалу', 'Тувалу', 'TV', 'TUV', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (800, 100000223, 'Уганда', 'Уганда', 'UG', 'UGA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (804, 100000226, 'Украина', 'Україна', 'UA', 'UKR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (807, 100000099, 'Бывшая Югославская Республика Македония', 'Колишня Югославська Республіка Македонія', 'MK', 'MKD', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (818, 100000071, 'Египет', 'Єгипет', 'EG', 'EGY', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (826, 100000037, 'Великобритания', 'Велика Британія', 'GB', 'GBR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (831, 100000056, 'Гернси', 'Гернсі', 'GG', 'GGY', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (832, 100000062, 'Джерси', 'Джерсі', 'JE', 'JEY', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (833, 100000157, 'Остров Мэн', 'Острів Мен', 'IM', 'IMN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (834, 100000213, 'Танзания, Объединенная Республика', 'Танзанія, Об''єднана Республіка', 'TZ', 'TZA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (840, 100000208, 'Сша', 'Сша', 'US', 'USA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (850, 100000041, 'Виргинские острова (США)', 'Віргінські острови (США)', 'VI', 'VIR', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (854, 100000033, 'Буркина-Фасо', 'Буркіна-Фасо', 'BF', 'BFA', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (858, 100000228, 'Уругвай', 'Уругвай', 'UY', 'URY', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (860, 100000225, 'Узбекистан', 'Узбекистан', 'UZ', 'UZB', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (862, 100000038, 'Венесуэла', 'Венесуела', 'VE', 'VEN', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (876, 100000227, 'Уоллис и Футуна', 'Уолліс і Футуна', 'WF', 'WLF', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (882, 100000183, 'Самоа', 'Самоа', 'WS', 'WSM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (887, 100000072, 'Йемен', 'Ємен', 'YE', 'YEM', '');
INSERT dbo.r_Countries(CounID, ChID, Country, UACountry, CountryCode2, CountryCode3, Notes) VALUES (894, 100000073, 'Замбия', 'Замбія', 'ZM', 'ZMB', '');
