INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (8, 100, 'Виртуальная касса', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (10, 600, 'Мария-301мтм-МТ3', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (11, 200, 'Datecs FP 3530T2', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (12, 1000, 'IKC-E260T (ЕП-02, ЕП-05)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (15, 400, 'Екселліо FPU-550, LP1000', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (18, 700, 'Мария-301мтм-МТ7', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (21, 1100, 'IKC-E260T (ЕП-06)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (22, 300, 'Datecs FP-T260, T88, 3530T (Протокол 4.00, 5.20)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (23, 1200, 'IKC-E810T (ЕП-08)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (29, 500, 'Екселліо FP2000', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (30, 1525, 'МІНІ-ФП, MINI-T (Протокол T400)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (31, 501, 'Екселліо Ethernet (Клиент)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (34, 350, 'Datecs FP-T260, T88, 3530T (Протокол 4.00, 5.20) Ethernet', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (36, 1202, 'IKC-C651T (ЕП-11)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (38, 710, 'Мария-304T1', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (39, 510, 'ПРРО', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (40, 713, 'Мария-304T-3', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (41, 750, 'Checkbox (программное)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (42, 714, 'Мария-304T-6', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (43, 550, 'KBM (протокол 5.00+)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (44, 551, 'KBM (протокол 5.00+) Ethernet', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (45, 505, 'Екселліо (протокол 4.00+)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (46, 506, 'Екселліо (протокол 4.00+) Ethernet', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (47, 751, 'Checkbox (программное) Ethernet', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (48, 752, 'SystemGroup (программное)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (49, 760, 'ПК-Сервис (программное)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (50, 761, 'ПК-Сервис Ethernet (программное)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (100, 1800, 'Екселліо (ЭККА)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (101, 2000, 'MINI-500.02ME, MINI-600.04ME', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (102, 1900, 'Екселліо DPU-450И (ЭККА)', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (103, 2100, 'Neon', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (104, 2125, 'Datecs MP-01', 1);
INSERT dbo.r_DeviceTypes(DeviceType, SrcPosID, DeviceTypeName, AllowChooseCashType) VALUES (1001, 2200, 'Интеграция с xPOS', 1);
