INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (0, 'Нет приложения', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (101, 'Общие документы', '');
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (102, 'Общие реестры', '');
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (103, 'Общие справочники', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (104, 'Общие прочие', '');
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (105, 'Общие отчеты', '');
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (200, 'Системные значения', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (700, 'Бухгалтерские отчеты', 'Внутреннее приложение для регистрации бухотчетов');
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (11000, 'Бизнес', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (11010, 'Торговый Клиент', '');
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (11020, 'Торговый сервер', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (12000, 'Финансы', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (14000, 'Бухгалтерия', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (14010, 'Банк', '');
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (15000, 'Кадры и Зарплата', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (18000, 'Анализатор', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (20000, 'Fast Food', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (21000, 'Ресторан', '');
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (22000, 'Услуги', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (24000, 'ПРРО: Перерегистрация офлайн документов', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (33000, 'Менеджер Доступа', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (37010, 'Менеджер синхронизации', NULL);
INSERT dbo.z_Apps(AppCode, AppName, AppInfo) VALUES (50000, 'Дизайнер Базы Данных', NULL);
