INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (0, 0, 'Общая бухгалтерская группа ТМЦ', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (201, 1, 'Сырье и материалы', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (202, 2, 'Покупные полуфабрикаты и комплектующие изделия', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (203, 3, 'Топливо', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (204, 4, 'Тара и тарные материалы', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (205, 5, 'Строительные материалы', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (206, 6, 'Материалы, переданные в переработку', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (207, 7, 'Запасные части', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (208, 8, 'Материалы сельскохозяйственного назначения', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (209, 9, 'Прочие материалы', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (211, 10, 'Молодняк животных на выращивании', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (212, 11, 'Животные на откорме', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (213, 12, 'Птица', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (214, 13, 'Звери', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (215, 14, 'Кроли', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (216, 15, 'Семьи пчел', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (217, 16, 'Взрослый скот, отбракованный из основного стада', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (218, 17, 'Скот, принятый от населения для реализации', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (220, 18, 'Малоценные и быстроизнашивающиеся предметы', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (250, 19, 'Полуфабрикаты', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (260, 20, 'Готовая продукция', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (270, 21, 'Продукция сельскохозяйственного производства', '', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (281, 26, 'Товары', '281, 282, 283 счета', 0);
INSERT dbo.r_ProdBG(PBGrID, ChID, PBGrName, Notes, Tare) VALUES (284, 25, 'Тара под товарами', '', 1);
