SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[p_LRecsE] WITH VIEW_METADATA AS
SELECT * FROM ( SELECT m.ChID,
m.DocID,
IntDocID,
m.OurID,
m.DocDate,
m.KursMC,
m.CodeID1,
m.CodeID2,
m.CodeID3,
m.CodeID4,
m.CodeID5,
d.SrcPosID,
d.EmpID,
d.DetSubID,
d.DetDepID,
AChID,
MainSumCC,
ExtraSumCC,
MoreSumCC,
NeglibleSumCC,
DeductionSumCC,
BTotPensCC,
BTotUnEmployCC,
BTotSocInsureCC,
BTotAccidentCC,
BIncomeTaxCC,
BPensCC,
BUnEmployCC,
BSocInsureCC,
BIndexing,
BPrivIncomeTax,
TotPensCC,
TotUnEmployCC,
TotSocInsureCC,
TotAccidentCC,
IncomeTaxCC,
PensCC,
UnEmployCC,
SocInsureCC,
ChargeSumCC,
GOperID,
GTranID
FROM p_LRec AS m INNER JOIN p_LRecD AS d ON d.ChID=m.ChID
) GMSView
GO