SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[p_CWTimeCors] WITH VIEW_METADATA AS
SELECT * FROM (
SELECT ChID, OurID, DocDate, DocID, CodeID1, CodeID2, CodeID3, CodeID4, CodeID5, EmpID, WTSignID, Notes, StateCode FROM p_CWTimeCor) GMSView
GO